
#ifndef _DOM_VOUT_CRG_MACRO_H_
#define _DOM_VOUT_CRG_MACRO_H_

//#define DOM_VOUT_CRG_BASE_ADDR 0x0
#define CLK_APB_CTRL_REG_ADDR                                        (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_DC8200_PIX0_CTRL_REG_ADDR                                (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_DSI_SYS_CTRL_REG_ADDR                                    (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_TX_ESC_CTRL_REG_ADDR                                     (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_U0_DC8200_CLK_AXI_CTRL_REG_ADDR                          (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_U0_DC8200_CLK_CORE_CTRL_REG_ADDR                         (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_U0_DC8200_CLK_AHB_CTRL_REG_ADDR                          (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR                         (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR                         (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR                       (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_U0_CDNS_DSITX_CLK_APB_CTRL_REG_ADDR                      (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x28U)
#define CLK_U0_CDNS_DSITX_CLK_SYS_CTRL_REG_ADDR                      (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR                      (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_U0_CDNS_DSITX_CLK_TXESC_CTRL_REG_ADDR                    (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_U0_MIPITX_DPHY_CLK_TXESC_CTRL_REG_ADDR                   (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_U0_HDMI_TX_CLK_MCLK_CTRL_REG_ADDR                        (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_U0_HDMI_TX_CLK_BCLK_CTRL_REG_ADDR                        (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_U0_HDMI_TX_CLK_SYS_CTRL_REG_ADDR                         (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x44U)


#define DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR          (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x48U)

#define DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR          (U0_DOM_VOUT_CRG__SAIF_BD_APBS__BASE_ADDR + 0x4CU)


#define CLK_APB_DIV_SHIFT                                            0
#define CLK_APB_DIV_MASK                                             0xFU
#define CLK_DC8200_PIX0_DIV_SHIFT                                    0
#define CLK_DC8200_PIX0_DIV_MASK                                     0x3FU
#define CLK_DSI_SYS_DIV_SHIFT                                        0
#define CLK_DSI_SYS_DIV_MASK                                         0x1FU
#define CLK_TX_ESC_DIV_SHIFT                                         0
#define CLK_TX_ESC_DIV_MASK                                          0x1FU
#define CLK_U0_DC8200_CLK_AXI_ENABLE_DATA                            1
#define CLK_U0_DC8200_CLK_AXI_DISABLE_DATA                           0
#define CLK_U0_DC8200_CLK_AXI_EN_SHIFT                               31
#define CLK_U0_DC8200_CLK_AXI_EN_MASK                                0x80000000U
#define CLK_U0_DC8200_CLK_CORE_ENABLE_DATA                           1
#define CLK_U0_DC8200_CLK_CORE_DISABLE_DATA                          0
#define CLK_U0_DC8200_CLK_CORE_EN_SHIFT                              31
#define CLK_U0_DC8200_CLK_CORE_EN_MASK                               0x80000000U
#define CLK_U0_DC8200_CLK_AHB_ENABLE_DATA                            1
#define CLK_U0_DC8200_CLK_AHB_DISABLE_DATA                           0
#define CLK_U0_DC8200_CLK_AHB_EN_SHIFT                               31
#define CLK_U0_DC8200_CLK_AHB_EN_MASK                                0x80000000U
#define CLK_U0_DC8200_CLK_PIX0_ENABLE_DATA                           1
#define CLK_U0_DC8200_CLK_PIX0_DISABLE_DATA                          0
#define CLK_U0_DC8200_CLK_PIX0_EN_SHIFT                              31
#define CLK_U0_DC8200_CLK_PIX0_EN_MASK                               0x80000000U
#define CLK_U0_DC8200_CLK_PIX0_SW_SHIFT                              24
#define CLK_U0_DC8200_CLK_PIX0_SW_MASK                               0x1000000U
#define CLK_U0_DC8200_CLK_PIX0_SW_CLK_DC8200_PIX0_DATA               0
#define CLK_U0_DC8200_CLK_PIX0_SW_CLK_HDMITX0_PIXELCLK_DATA          1
#define CLK_U0_DC8200_CLK_PIX1_ENABLE_DATA                           1
#define CLK_U0_DC8200_CLK_PIX1_DISABLE_DATA                          0
#define CLK_U0_DC8200_CLK_PIX1_EN_SHIFT                              31
#define CLK_U0_DC8200_CLK_PIX1_EN_MASK                               0x80000000U
#define CLK_U0_DC8200_CLK_PIX1_SW_SHIFT                              24
#define CLK_U0_DC8200_CLK_PIX1_SW_MASK                               0x1000000U
#define CLK_U0_DC8200_CLK_PIX1_SW_CLK_DC8200_PIX0_DATA               0
#define CLK_U0_DC8200_CLK_PIX1_SW_CLK_HDMITX0_PIXELCLK_DATA          1
#define CLK_DOM_VOUT_TOP_LCD_CLK_ENABLE_DATA                         1
#define CLK_DOM_VOUT_TOP_LCD_CLK_DISABLE_DATA                        0
#define CLK_DOM_VOUT_TOP_LCD_CLK_EN_SHIFT                            31
#define CLK_DOM_VOUT_TOP_LCD_CLK_EN_MASK                             0x80000000U
#define CLK_DOM_VOUT_TOP_LCD_CLK_SW_SHIFT                            24
#define CLK_DOM_VOUT_TOP_LCD_CLK_SW_MASK                             0x1000000U
#define CLK_DOM_VOUT_TOP_LCD_CLK_SW_CLK_U0_DC8200_CLK_PIX0_OUT_DATA  0
#define CLK_DOM_VOUT_TOP_LCD_CLK_SW_CLK_U0_DC8200_CLK_PIX1_OUT_DATA  1
#define CLK_U0_CDNS_DSITX_CLK_APB_ENABLE_DATA                        1
#define CLK_U0_CDNS_DSITX_CLK_APB_DISABLE_DATA                       0
#define CLK_U0_CDNS_DSITX_CLK_APB_EN_SHIFT                           31
#define CLK_U0_CDNS_DSITX_CLK_APB_EN_MASK                            0x80000000U
#define CLK_U0_CDNS_DSITX_CLK_SYS_ENABLE_DATA                        1
#define CLK_U0_CDNS_DSITX_CLK_SYS_DISABLE_DATA                       0
#define CLK_U0_CDNS_DSITX_CLK_SYS_EN_SHIFT                           31
#define CLK_U0_CDNS_DSITX_CLK_SYS_EN_MASK                            0x80000000U
#define CLK_U0_CDNS_DSITX_CLK_DPI_ENABLE_DATA                        1
#define CLK_U0_CDNS_DSITX_CLK_DPI_DISABLE_DATA                       0
#define CLK_U0_CDNS_DSITX_CLK_DPI_EN_SHIFT                           31
#define CLK_U0_CDNS_DSITX_CLK_DPI_EN_MASK                            0x80000000U
#define CLK_U0_CDNS_DSITX_CLK_DPI_SW_SHIFT                           24
#define CLK_U0_CDNS_DSITX_CLK_DPI_SW_MASK                            0x1000000U
#define CLK_U0_CDNS_DSITX_CLK_DPI_SW_CLK_DC8200_PIX0_DATA            0
#define CLK_U0_CDNS_DSITX_CLK_DPI_SW_CLK_HDMITX0_PIXELCLK_DATA       1
#define CLK_U0_CDNS_DSITX_CLK_TXESC_ENABLE_DATA                      1
#define CLK_U0_CDNS_DSITX_CLK_TXESC_DISABLE_DATA                     0
#define CLK_U0_CDNS_DSITX_CLK_TXESC_EN_SHIFT                         31
#define CLK_U0_CDNS_DSITX_CLK_TXESC_EN_MASK                          0x80000000U
#define CLK_U0_MIPITX_DPHY_CLK_TXESC_ENABLE_DATA                     1
#define CLK_U0_MIPITX_DPHY_CLK_TXESC_DISABLE_DATA                    0
#define CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_SHIFT                        31
#define CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_MASK                         0x80000000U
#define CLK_U0_HDMI_TX_CLK_MCLK_ENABLE_DATA                          1
#define CLK_U0_HDMI_TX_CLK_MCLK_DISABLE_DATA                         0
#define CLK_U0_HDMI_TX_CLK_MCLK_EN_SHIFT                             31
#define CLK_U0_HDMI_TX_CLK_MCLK_EN_MASK                              0x80000000U
#define CLK_U0_HDMI_TX_CLK_BCLK_ENABLE_DATA                          1
#define CLK_U0_HDMI_TX_CLK_BCLK_DISABLE_DATA                         0
#define CLK_U0_HDMI_TX_CLK_BCLK_EN_SHIFT                             31
#define CLK_U0_HDMI_TX_CLK_BCLK_EN_MASK                              0x80000000U
#define CLK_U0_HDMI_TX_CLK_SYS_ENABLE_DATA                           1
#define CLK_U0_HDMI_TX_CLK_SYS_DISABLE_DATA                          0
#define CLK_U0_HDMI_TX_CLK_SYS_EN_SHIFT                              31
#define CLK_U0_HDMI_TX_CLK_SYS_EN_MASK                               0x80000000U



#define RSTN_U0_DC8200_RSTN_AXI_SHIFT                                0
#define RSTN_U0_DC8200_RSTN_AXI_MASK                                 (0x1 << 0)
#define RSTN_U0_DC8200_RSTN_AXI_ASSERT                               1
#define RSTN_U0_DC8200_RSTN_AXI_CLEAR                                0
#define RSTN_U0_DC8200_RSTN_AHB_SHIFT                                1
#define RSTN_U0_DC8200_RSTN_AHB_MASK                                 (0x1 << 1)
#define RSTN_U0_DC8200_RSTN_AHB_ASSERT                               1
#define RSTN_U0_DC8200_RSTN_AHB_CLEAR                                0
#define RSTN_U0_DC8200_RSTN_CORE_SHIFT                               2
#define RSTN_U0_DC8200_RSTN_CORE_MASK                                (0x1 << 2)
#define RSTN_U0_DC8200_RSTN_CORE_ASSERT                              1
#define RSTN_U0_DC8200_RSTN_CORE_CLEAR                               0
#define RSTN_U0_CDNS_DSITX_RSTN_DPI_SHIFT                            3
#define RSTN_U0_CDNS_DSITX_RSTN_DPI_MASK                             (0x1 << 3)
#define RSTN_U0_CDNS_DSITX_RSTN_DPI_ASSERT                           1
#define RSTN_U0_CDNS_DSITX_RSTN_DPI_CLEAR                            0
#define RSTN_U0_CDNS_DSITX_RSTN_APB_SHIFT                            4
#define RSTN_U0_CDNS_DSITX_RSTN_APB_MASK                             (0x1 << 4)
#define RSTN_U0_CDNS_DSITX_RSTN_APB_ASSERT                           1
#define RSTN_U0_CDNS_DSITX_RSTN_APB_CLEAR                            0
#define RSTN_U0_CDNS_DSITX_RSTN_RXESC_SHIFT                          5
#define RSTN_U0_CDNS_DSITX_RSTN_RXESC_MASK                           (0x1 << 5)
#define RSTN_U0_CDNS_DSITX_RSTN_RXESC_ASSERT                         1
#define RSTN_U0_CDNS_DSITX_RSTN_RXESC_CLEAR                          0
#define RSTN_U0_CDNS_DSITX_RSTN_SYS_SHIFT                            6
#define RSTN_U0_CDNS_DSITX_RSTN_SYS_MASK                             (0x1 << 6)
#define RSTN_U0_CDNS_DSITX_RSTN_SYS_ASSERT                           1
#define RSTN_U0_CDNS_DSITX_RSTN_SYS_CLEAR                            0
#define RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_SHIFT                       7
#define RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_MASK                        (0x1 << 7)
#define RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_ASSERT                      1
#define RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_CLEAR                       0
#define RSTN_U0_CDNS_DSITX_RSTN_TXESC_SHIFT                          8
#define RSTN_U0_CDNS_DSITX_RSTN_TXESC_MASK                           (0x1 << 8)
#define RSTN_U0_CDNS_DSITX_RSTN_TXESC_ASSERT                         1
#define RSTN_U0_CDNS_DSITX_RSTN_TXESC_CLEAR                          0
#define RSTN_U0_HDMI_TX_RSTN_HDMI_SHIFT                              9
#define RSTN_U0_HDMI_TX_RSTN_HDMI_MASK                               (0x1 << 9)
#define RSTN_U0_HDMI_TX_RSTN_HDMI_ASSERT                             1
#define RSTN_U0_HDMI_TX_RSTN_HDMI_CLEAR                              0
#define RSTN_U0_MIPITX_DPHY_RSTN_SYS_SHIFT                           10
#define RSTN_U0_MIPITX_DPHY_RSTN_SYS_MASK                            (0x1 << 10)
#define RSTN_U0_MIPITX_DPHY_RSTN_SYS_ASSERT                          1
#define RSTN_U0_MIPITX_DPHY_RSTN_SYS_CLEAR                           0
#define RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_SHIFT                      11
#define RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_MASK                       (0x1 << 11)
#define RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_ASSERT                     1
#define RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_CLEAR                      0

#define _DIVIDE_CLOCK_CLK_APB_(div) 			saif_set_reg(CLK_APB_CTRL_REG_ADDR, div, CLK_APB_DIV_SHIFT, CLK_APB_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_APB_ 		saif_get_reg(CLK_APB_CTRL_REG_ADDR, CLK_APB_DIV_SHIFT, CLK_APB_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_DC8200_PIX0_(div) 			saif_set_reg(CLK_DC8200_PIX0_CTRL_REG_ADDR, div, CLK_DC8200_PIX0_DIV_SHIFT, CLK_DC8200_PIX0_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_DC8200_PIX0_ 		saif_get_reg(CLK_DC8200_PIX0_CTRL_REG_ADDR, CLK_DC8200_PIX0_DIV_SHIFT, CLK_DC8200_PIX0_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_DSI_SYS_(div) 			saif_set_reg(CLK_DSI_SYS_CTRL_REG_ADDR, div, CLK_DSI_SYS_DIV_SHIFT, CLK_DSI_SYS_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_DSI_SYS_ 		saif_get_reg(CLK_DSI_SYS_CTRL_REG_ADDR, CLK_DSI_SYS_DIV_SHIFT, CLK_DSI_SYS_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_TX_ESC_(div) 			saif_set_reg(CLK_TX_ESC_CTRL_REG_ADDR, div, CLK_TX_ESC_DIV_SHIFT, CLK_TX_ESC_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_TX_ESC_ 		saif_get_reg(CLK_TX_ESC_CTRL_REG_ADDR, CLK_TX_ESC_DIV_SHIFT, CLK_TX_ESC_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_DC8200_CLK_AXI_ 			saif_set_reg(CLK_U0_DC8200_CLK_AXI_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_AXI_ENABLE_DATA, CLK_U0_DC8200_CLK_AXI_EN_SHIFT, CLK_U0_DC8200_CLK_AXI_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DC8200_CLK_AXI_ 			saif_set_reg(CLK_U0_DC8200_CLK_AXI_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_AXI_DISABLE_DATA, CLK_U0_DC8200_CLK_AXI_EN_SHIFT, CLK_U0_DC8200_CLK_AXI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_AXI_ 		saif_get_reg(CLK_U0_DC8200_CLK_AXI_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_AXI_EN_SHIFT, CLK_U0_DC8200_CLK_AXI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_AXI_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_AXI_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_AXI_EN_SHIFT, CLK_U0_DC8200_CLK_AXI_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DC8200_CLK_CORE_ 			saif_set_reg(CLK_U0_DC8200_CLK_CORE_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_CORE_ENABLE_DATA, CLK_U0_DC8200_CLK_CORE_EN_SHIFT, CLK_U0_DC8200_CLK_CORE_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DC8200_CLK_CORE_ 			saif_set_reg(CLK_U0_DC8200_CLK_CORE_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_CORE_DISABLE_DATA, CLK_U0_DC8200_CLK_CORE_EN_SHIFT, CLK_U0_DC8200_CLK_CORE_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_CORE_ 		saif_get_reg(CLK_U0_DC8200_CLK_CORE_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_CORE_EN_SHIFT, CLK_U0_DC8200_CLK_CORE_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_CORE_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_CORE_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_CORE_EN_SHIFT, CLK_U0_DC8200_CLK_CORE_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DC8200_CLK_AHB_ 			saif_set_reg(CLK_U0_DC8200_CLK_AHB_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_AHB_ENABLE_DATA, CLK_U0_DC8200_CLK_AHB_EN_SHIFT, CLK_U0_DC8200_CLK_AHB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DC8200_CLK_AHB_ 			saif_set_reg(CLK_U0_DC8200_CLK_AHB_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_AHB_DISABLE_DATA, CLK_U0_DC8200_CLK_AHB_EN_SHIFT, CLK_U0_DC8200_CLK_AHB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_AHB_ 		saif_get_reg(CLK_U0_DC8200_CLK_AHB_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_AHB_EN_SHIFT, CLK_U0_DC8200_CLK_AHB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_AHB_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_AHB_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_AHB_EN_SHIFT, CLK_U0_DC8200_CLK_AHB_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DC8200_CLK_PIX0_ 			saif_set_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX0_ENABLE_DATA, CLK_U0_DC8200_CLK_PIX0_EN_SHIFT, CLK_U0_DC8200_CLK_PIX0_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DC8200_CLK_PIX0_ 			saif_set_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX0_DISABLE_DATA, CLK_U0_DC8200_CLK_PIX0_EN_SHIFT, CLK_U0_DC8200_CLK_PIX0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_PIX0_ 		saif_get_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX0_EN_SHIFT, CLK_U0_DC8200_CLK_PIX0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_PIX0_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_PIX0_EN_SHIFT, CLK_U0_DC8200_CLK_PIX0_EN_MASK)
#define _SWITCH_CLOCK_CLK_U0_DC8200_CLK_PIX0_SOURCE_CLK_DC8200_PIX0_ 	saif_set_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX0_SW_CLK_DC8200_PIX0_DATA, CLK_U0_DC8200_CLK_PIX0_SW_SHIFT, CLK_U0_DC8200_CLK_PIX0_SW_MASK)
#define _SWITCH_CLOCK_CLK_U0_DC8200_CLK_PIX0_SOURCE_CLK_HDMITX0_PIXELCLK_ 	saif_set_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX0_SW_CLK_HDMITX0_PIXELCLK_DATA, CLK_U0_DC8200_CLK_PIX0_SW_SHIFT, CLK_U0_DC8200_CLK_PIX0_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_U0_DC8200_CLK_PIX0_ 		saif_get_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX0_SW_SHIFT, CLK_U0_DC8200_CLK_PIX0_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_U0_DC8200_CLK_PIX0_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_PIX0_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_PIX0_SW_SHIFT, CLK_U0_DC8200_CLK_PIX0_SW_MASK)
#define _ENABLE_CLOCK_CLK_U0_DC8200_CLK_PIX1_ 			saif_set_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX1_ENABLE_DATA, CLK_U0_DC8200_CLK_PIX1_EN_SHIFT, CLK_U0_DC8200_CLK_PIX1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DC8200_CLK_PIX1_ 			saif_set_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX1_DISABLE_DATA, CLK_U0_DC8200_CLK_PIX1_EN_SHIFT, CLK_U0_DC8200_CLK_PIX1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_PIX1_ 		saif_get_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX1_EN_SHIFT, CLK_U0_DC8200_CLK_PIX1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DC8200_CLK_PIX1_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_PIX1_EN_SHIFT, CLK_U0_DC8200_CLK_PIX1_EN_MASK)
#define _SWITCH_CLOCK_CLK_U0_DC8200_CLK_PIX1_SOURCE_CLK_DC8200_PIX0_ 	saif_set_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX1_SW_CLK_DC8200_PIX0_DATA, CLK_U0_DC8200_CLK_PIX1_SW_SHIFT, CLK_U0_DC8200_CLK_PIX1_SW_MASK)
#define _SWITCH_CLOCK_CLK_U0_DC8200_CLK_PIX1_SOURCE_CLK_HDMITX0_PIXELCLK_ 	saif_set_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX1_SW_CLK_HDMITX0_PIXELCLK_DATA, CLK_U0_DC8200_CLK_PIX1_SW_SHIFT, CLK_U0_DC8200_CLK_PIX1_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_U0_DC8200_CLK_PIX1_ 		saif_get_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, CLK_U0_DC8200_CLK_PIX1_SW_SHIFT, CLK_U0_DC8200_CLK_PIX1_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_U0_DC8200_CLK_PIX1_(x) 		saif_set_reg(CLK_U0_DC8200_CLK_PIX1_CTRL_REG_ADDR, x, CLK_U0_DC8200_CLK_PIX1_SW_SHIFT, CLK_U0_DC8200_CLK_PIX1_SW_MASK)
#define _ENABLE_CLOCK_CLK_DOM_VOUT_TOP_LCD_CLK_ 			saif_set_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, CLK_DOM_VOUT_TOP_LCD_CLK_ENABLE_DATA, CLK_DOM_VOUT_TOP_LCD_CLK_EN_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_DOM_VOUT_TOP_LCD_CLK_ 			saif_set_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, CLK_DOM_VOUT_TOP_LCD_CLK_DISABLE_DATA, CLK_DOM_VOUT_TOP_LCD_CLK_EN_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_DOM_VOUT_TOP_LCD_CLK_ 		saif_get_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, CLK_DOM_VOUT_TOP_LCD_CLK_EN_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_DOM_VOUT_TOP_LCD_CLK_(x) 		saif_set_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, x, CLK_DOM_VOUT_TOP_LCD_CLK_EN_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_EN_MASK)
#define _SWITCH_CLOCK_CLK_DOM_VOUT_TOP_LCD_CLK_SOURCE_CLK_U0_DC8200_CLK_PIX0_OUT_ 	saif_set_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, CLK_DOM_VOUT_TOP_LCD_CLK_SW_CLK_U0_DC8200_CLK_PIX0_OUT_DATA, CLK_DOM_VOUT_TOP_LCD_CLK_SW_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_SW_MASK)
#define _SWITCH_CLOCK_CLK_DOM_VOUT_TOP_LCD_CLK_SOURCE_CLK_U0_DC8200_CLK_PIX1_OUT_ 	saif_set_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, CLK_DOM_VOUT_TOP_LCD_CLK_SW_CLK_U0_DC8200_CLK_PIX1_OUT_DATA, CLK_DOM_VOUT_TOP_LCD_CLK_SW_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_DOM_VOUT_TOP_LCD_CLK_ 		saif_get_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, CLK_DOM_VOUT_TOP_LCD_CLK_SW_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_DOM_VOUT_TOP_LCD_CLK_(x) 		saif_set_reg(CLK_DOM_VOUT_TOP_LCD_CLK_CTRL_REG_ADDR, x, CLK_DOM_VOUT_TOP_LCD_CLK_SW_SHIFT, CLK_DOM_VOUT_TOP_LCD_CLK_SW_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_APB_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_APB_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_APB_ENABLE_DATA, CLK_U0_CDNS_DSITX_CLK_APB_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_APB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_APB_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_APB_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_APB_DISABLE_DATA, CLK_U0_CDNS_DSITX_CLK_APB_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_APB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_APB_ 		saif_get_reg(CLK_U0_CDNS_DSITX_CLK_APB_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_APB_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_APB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_APB_(x) 		saif_set_reg(CLK_U0_CDNS_DSITX_CLK_APB_CTRL_REG_ADDR, x, CLK_U0_CDNS_DSITX_CLK_APB_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_APB_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_SYS_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_SYS_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_SYS_ENABLE_DATA, CLK_U0_CDNS_DSITX_CLK_SYS_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_SYS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_SYS_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_SYS_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_SYS_DISABLE_DATA, CLK_U0_CDNS_DSITX_CLK_SYS_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_SYS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_SYS_ 		saif_get_reg(CLK_U0_CDNS_DSITX_CLK_SYS_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_SYS_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_SYS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_SYS_(x) 		saif_set_reg(CLK_U0_CDNS_DSITX_CLK_SYS_CTRL_REG_ADDR, x, CLK_U0_CDNS_DSITX_CLK_SYS_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_SYS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_DPI_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_DPI_ENABLE_DATA, CLK_U0_CDNS_DSITX_CLK_DPI_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_DPI_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_DPI_DISABLE_DATA, CLK_U0_CDNS_DSITX_CLK_DPI_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_DPI_ 		saif_get_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_DPI_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_DPI_(x) 		saif_set_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, x, CLK_U0_CDNS_DSITX_CLK_DPI_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_EN_MASK)
#define _SWITCH_CLOCK_CLK_U0_CDNS_DSITX_CLK_DPI_SOURCE_CLK_DC8200_PIX0_ 	saif_set_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_DPI_SW_CLK_DC8200_PIX0_DATA, CLK_U0_CDNS_DSITX_CLK_DPI_SW_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_SW_MASK)
#define _SWITCH_CLOCK_CLK_U0_CDNS_DSITX_CLK_DPI_SOURCE_CLK_HDMITX0_PIXELCLK_ 	saif_set_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_DPI_SW_CLK_HDMITX0_PIXELCLK_DATA, CLK_U0_CDNS_DSITX_CLK_DPI_SW_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_U0_CDNS_DSITX_CLK_DPI_ 		saif_get_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_DPI_SW_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_U0_CDNS_DSITX_CLK_DPI_(x) 		saif_set_reg(CLK_U0_CDNS_DSITX_CLK_DPI_CTRL_REG_ADDR, x, CLK_U0_CDNS_DSITX_CLK_DPI_SW_SHIFT, CLK_U0_CDNS_DSITX_CLK_DPI_SW_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_TXESC_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_TXESC_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_TXESC_ENABLE_DATA, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDNS_DSITX_CLK_TXESC_ 			saif_set_reg(CLK_U0_CDNS_DSITX_CLK_TXESC_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_TXESC_DISABLE_DATA, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_TXESC_ 		saif_get_reg(CLK_U0_CDNS_DSITX_CLK_TXESC_CTRL_REG_ADDR, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDNS_DSITX_CLK_TXESC_(x) 		saif_set_reg(CLK_U0_CDNS_DSITX_CLK_TXESC_CTRL_REG_ADDR, x, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_SHIFT, CLK_U0_CDNS_DSITX_CLK_TXESC_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_MIPITX_DPHY_CLK_TXESC_ 			saif_set_reg(CLK_U0_MIPITX_DPHY_CLK_TXESC_CTRL_REG_ADDR, CLK_U0_MIPITX_DPHY_CLK_TXESC_ENABLE_DATA, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_SHIFT, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_MIPITX_DPHY_CLK_TXESC_ 			saif_set_reg(CLK_U0_MIPITX_DPHY_CLK_TXESC_CTRL_REG_ADDR, CLK_U0_MIPITX_DPHY_CLK_TXESC_DISABLE_DATA, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_SHIFT, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_MIPITX_DPHY_CLK_TXESC_ 		saif_get_reg(CLK_U0_MIPITX_DPHY_CLK_TXESC_CTRL_REG_ADDR, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_SHIFT, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_MIPITX_DPHY_CLK_TXESC_(x) 		saif_set_reg(CLK_U0_MIPITX_DPHY_CLK_TXESC_CTRL_REG_ADDR, x, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_SHIFT, CLK_U0_MIPITX_DPHY_CLK_TXESC_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_HDMI_TX_CLK_MCLK_ 			saif_set_reg(CLK_U0_HDMI_TX_CLK_MCLK_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_MCLK_ENABLE_DATA, CLK_U0_HDMI_TX_CLK_MCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_MCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_HDMI_TX_CLK_MCLK_ 			saif_set_reg(CLK_U0_HDMI_TX_CLK_MCLK_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_MCLK_DISABLE_DATA, CLK_U0_HDMI_TX_CLK_MCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_MCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_HDMI_TX_CLK_MCLK_ 		saif_get_reg(CLK_U0_HDMI_TX_CLK_MCLK_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_MCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_MCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_HDMI_TX_CLK_MCLK_(x) 		saif_set_reg(CLK_U0_HDMI_TX_CLK_MCLK_CTRL_REG_ADDR, x, CLK_U0_HDMI_TX_CLK_MCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_MCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_HDMI_TX_CLK_BCLK_ 			saif_set_reg(CLK_U0_HDMI_TX_CLK_BCLK_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_BCLK_ENABLE_DATA, CLK_U0_HDMI_TX_CLK_BCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_BCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_HDMI_TX_CLK_BCLK_ 			saif_set_reg(CLK_U0_HDMI_TX_CLK_BCLK_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_BCLK_DISABLE_DATA, CLK_U0_HDMI_TX_CLK_BCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_BCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_HDMI_TX_CLK_BCLK_ 		saif_get_reg(CLK_U0_HDMI_TX_CLK_BCLK_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_BCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_BCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_HDMI_TX_CLK_BCLK_(x) 		saif_set_reg(CLK_U0_HDMI_TX_CLK_BCLK_CTRL_REG_ADDR, x, CLK_U0_HDMI_TX_CLK_BCLK_EN_SHIFT, CLK_U0_HDMI_TX_CLK_BCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_HDMI_TX_CLK_SYS_ 			saif_set_reg(CLK_U0_HDMI_TX_CLK_SYS_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_SYS_ENABLE_DATA, CLK_U0_HDMI_TX_CLK_SYS_EN_SHIFT, CLK_U0_HDMI_TX_CLK_SYS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_HDMI_TX_CLK_SYS_ 			saif_set_reg(CLK_U0_HDMI_TX_CLK_SYS_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_SYS_DISABLE_DATA, CLK_U0_HDMI_TX_CLK_SYS_EN_SHIFT, CLK_U0_HDMI_TX_CLK_SYS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_HDMI_TX_CLK_SYS_ 		saif_get_reg(CLK_U0_HDMI_TX_CLK_SYS_CTRL_REG_ADDR, CLK_U0_HDMI_TX_CLK_SYS_EN_SHIFT, CLK_U0_HDMI_TX_CLK_SYS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_HDMI_TX_CLK_SYS_(x) 		saif_set_reg(CLK_U0_HDMI_TX_CLK_SYS_CTRL_REG_ADDR, x, CLK_U0_HDMI_TX_CLK_SYS_EN_SHIFT, CLK_U0_HDMI_TX_CLK_SYS_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DC8200_RSTN_AXI_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_AXI_SHIFT, RSTN_U0_DC8200_RSTN_AXI_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DC8200_RSTN_AXI_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_AXI_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DC8200_RSTN_AXI_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_AXI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DC8200_RSTN_AHB_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_AHB_SHIFT, RSTN_U0_DC8200_RSTN_AHB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DC8200_RSTN_AHB_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_AHB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DC8200_RSTN_AHB_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_AHB_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DC8200_RSTN_CORE_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_CORE_SHIFT, RSTN_U0_DC8200_RSTN_CORE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DC8200_RSTN_CORE_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_CORE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DC8200_RSTN_CORE_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DC8200_RSTN_CORE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_DPI_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_DPI_SHIFT, RSTN_U0_CDNS_DSITX_RSTN_DPI_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_DPI_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_DPI_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_DPI_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_DPI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_APB_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_APB_SHIFT, RSTN_U0_CDNS_DSITX_RSTN_APB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_APB_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_APB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_APB_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_APB_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_RXESC_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_RXESC_SHIFT, RSTN_U0_CDNS_DSITX_RSTN_RXESC_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_RXESC_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_RXESC_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_RXESC_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_RXESC_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_SYS_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_SYS_SHIFT, RSTN_U0_CDNS_DSITX_RSTN_SYS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_SYS_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_SYS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_SYS_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_SYS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_SHIFT, RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_TXBYTEHS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_TXESC_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_TXESC_SHIFT, RSTN_U0_CDNS_DSITX_RSTN_TXESC_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_TXESC_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_TXESC_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDNS_DSITX_RSTN_TXESC_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDNS_DSITX_RSTN_TXESC_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_HDMI_TX_RSTN_HDMI_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_HDMI_TX_RSTN_HDMI_SHIFT, RSTN_U0_HDMI_TX_RSTN_HDMI_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_HDMI_TX_RSTN_HDMI_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_HDMI_TX_RSTN_HDMI_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_HDMI_TX_RSTN_HDMI_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_HDMI_TX_RSTN_HDMI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_MIPITX_DPHY_RSTN_SYS_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_MIPITX_DPHY_RSTN_SYS_SHIFT, RSTN_U0_MIPITX_DPHY_RSTN_SYS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_MIPITX_DPHY_RSTN_SYS_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_MIPITX_DPHY_RSTN_SYS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_MIPITX_DPHY_RSTN_SYS_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_MIPITX_DPHY_RSTN_SYS_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_ 	saif_get_reg(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_SHIFT, RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_ 	saif_assert_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_ 	saif_clear_rst(DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, DOM_VOUT_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_MIPITX_DPHY_RSTN_TXBYTEHS_MASK)


#endif //_DOM_VOUT_CRG_MACRO_H_
