PORT_CFLAGS = -DPERFORMANCE_RUN=1 -DMAIN_HAS_NOARGC=1 -DHAS_STDIO -DHAS_PRINTF -DHAS_TIME_H -DUSE_CLOCK -DHAS_FLOAT=0 -DITERATIONS=0

FLAGS_STR = "$(PORT_CFLAGS)"
override CFLAGS += $(PORT_CFLAGS) -DFLAGS_STR=\"$(FLAGS_STR)\"

INCLUDE_DIRS += \
	$(COREMARK_DIR) \
	$(COREMARK_DIR)/freedom-metal \

SOURCE_DIRS += \
	$(COREMARK_DIR) \
	$(COREMARK_DIR)/freedom-metal \
