#define AON_SYSCONSAIF__SYSCFG_0_ADDR                      (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x0U)
#define AON_GP_REG_WIDTH                                   0x20U
#define AON_GP_REG_SHIFT                                   0x0U
#define AON_GP_REG_MASK                                    0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_4_ADDR                      (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x4U)
#define U0_BOOT_CTRL_BOOT_STATUS_WIDTH                     0x4U
#define U0_BOOT_CTRL_BOOT_STATUS_SHIFT                     0x0U
#define U0_BOOT_CTRL_BOOT_STATUS_MASK                      0xFU
#define AON_SYSCONSAIF__SYSCFG_8_ADDR                      (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x8U)
#define U0_BOOT_CTRL_BOOT_VECTOR_31_0__WIDTH               0x20U
#define U0_BOOT_CTRL_BOOT_VECTOR_31_0__SHIFT               0x0U
#define U0_BOOT_CTRL_BOOT_VECTOR_31_0__MASK                0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_12_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0xcU)
#define U0_BOOT_CTRL_BOOT_VECTOR_35_32__WIDTH              0x4U
#define U0_BOOT_CTRL_BOOT_VECTOR_35_32__SHIFT              0x0U
#define U0_BOOT_CTRL_BOOT_VECTOR_35_32__MASK               0xFU
#define U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_WIDTH               0xCU
#define U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_SHIFT               0x4U
#define U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_MASK                0xFFF0U
#define U0_DW_GMAC5_AXI64_MAC_SPEED_O_WIDTH                0x2U
#define U0_DW_GMAC5_AXI64_MAC_SPEED_O_SHIFT                0x10U
#define U0_DW_GMAC5_AXI64_MAC_SPEED_O_MASK                 0x30000U
#define U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_WIDTH             0x3U
#define U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_SHIFT             0x12U
#define U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_MASK              0x1C0000U
#define AON_SYSCONSAIF__SYSCFG_16_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x10U)
#define U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_31_0__WIDTH      0x20U
#define U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_31_0__SHIFT      0x0U
#define U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_31_0__MASK       0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_20_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x14U)
#define U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_63_32__WIDTH     0x20U
#define U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_63_32__SHIFT     0x0U
#define U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_63_32__MASK      0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_24_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x18U)
#define U0_OTPC_CHIP_MODE_WIDTH                            0x1U
#define U0_OTPC_CHIP_MODE_SHIFT                            0x0U
#define U0_OTPC_CHIP_MODE_MASK                             0x1U
#define U0_OTPC_CRC_PASS_WIDTH                             0x1U
#define U0_OTPC_CRC_PASS_SHIFT                             0x1U
#define U0_OTPC_CRC_PASS_MASK                              0x2U
#define U0_OTPC_DBG_ENABLE_WIDTH                           0x1U
#define U0_OTPC_DBG_ENABLE_SHIFT                           0x2U
#define U0_OTPC_DBG_ENABLE_MASK                            0x4U
#define AON_SYSCONSAIF__SYSCFG_28_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x1cU)
#define U0_OTPC_FL_FUNC_LOCK_WIDTH                         0x20U
#define U0_OTPC_FL_FUNC_LOCK_SHIFT                         0x0U
#define U0_OTPC_FL_FUNC_LOCK_MASK                          0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_32_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x20U)
#define U0_OTPC_FL_PLL0_LOCK_WIDTH                         0x20U
#define U0_OTPC_FL_PLL0_LOCK_SHIFT                         0x0U
#define U0_OTPC_FL_PLL0_LOCK_MASK                          0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_36_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x24U)
#define U0_OTPC_FL_PLL1_LOCK_WIDTH                         0x20U
#define U0_OTPC_FL_PLL1_LOCK_SHIFT                         0x0U
#define U0_OTPC_FL_PLL1_LOCK_MASK                          0xFFFFFFFFU
#define AON_SYSCONSAIF__SYSCFG_40_ADDR                     (U0_AON_SYSCON__SAIF_BD_APBS__BASE_ADDR + 0x28U)
#define U0_OTPC_FL_SEC_BOOT_LMT_WIDTH                      0x1U
#define U0_OTPC_FL_SEC_BOOT_LMT_SHIFT                      0x0U
#define U0_OTPC_FL_SEC_BOOT_LMT_MASK                       0x1U
#define U0_OTPC_FL_XIP_WIDTH                               0x1U
#define U0_OTPC_FL_XIP_SHIFT                               0x1U
#define U0_OTPC_FL_XIP_MASK                                0x2U
#define U0_OTPC_LOAD_BUSY_WIDTH                            0x1U
#define U0_OTPC_LOAD_BUSY_SHIFT                            0x2U
#define U0_OTPC_LOAD_BUSY_MASK                             0x4U
#define U0_RESET_CTRL_CLR_RESET_STATUS_WIDTH               0x1U
#define U0_RESET_CTRL_CLR_RESET_STATUS_SHIFT               0x3U
#define U0_RESET_CTRL_CLR_RESET_STATUS_MASK                0x8U
#define U0_RESET_CTRL_PLL_TIMECNT_FINISH_WIDTH             0x1U
#define U0_RESET_CTRL_PLL_TIMECNT_FINISH_SHIFT             0x4U
#define U0_RESET_CTRL_PLL_TIMECNT_FINISH_MASK              0x10U
#define U0_RESET_CTRL_RSTN_SW_WIDTH                        0x1U
#define U0_RESET_CTRL_RSTN_SW_SHIFT                        0x5U
#define U0_RESET_CTRL_RSTN_SW_MASK                         0x20U
#define U0_RESET_CTRL_SYS_RESET_STATUS_WIDTH               0x4U
#define U0_RESET_CTRL_SYS_RESET_STATUS_SHIFT               0x6U
#define U0_RESET_CTRL_SYS_RESET_STATUS_MASK                0x3C0U
#define GET_AON_GP_REG                                     saif_get_reg(AON_SYSCONSAIF__SYSCFG_0_ADDR,AON_GP_REG_SHIFT,AON_GP_REG_MASK)
#define SET_AON_GP_REG(data)                               saif_set_reg(AON_SYSCONSAIF__SYSCFG_0_ADDR,data,AON_GP_REG_SHIFT,AON_GP_REG_MASK)
#define GET_U0_BOOT_CTRL_BOOT_STATUS                       saif_get_reg(AON_SYSCONSAIF__SYSCFG_4_ADDR,U0_BOOT_CTRL_BOOT_STATUS_SHIFT,U0_BOOT_CTRL_BOOT_STATUS_MASK)
#define GET_U0_BOOT_CTRL_BOOT_VECTOR_31_0_                 saif_get_reg(AON_SYSCONSAIF__SYSCFG_8_ADDR,U0_BOOT_CTRL_BOOT_VECTOR_31_0__SHIFT,U0_BOOT_CTRL_BOOT_VECTOR_31_0__MASK)
#define GET_U0_BOOT_CTRL_BOOT_VECTOR_35_32_                saif_get_reg(AON_SYSCONSAIF__SYSCFG_12_ADDR,U0_BOOT_CTRL_BOOT_VECTOR_35_32__SHIFT,U0_BOOT_CTRL_BOOT_VECTOR_35_32__MASK)
#define GET_U0_DW_GMAC5_AXI64_SCFG_RAM_CFG                 saif_get_reg(AON_SYSCONSAIF__SYSCFG_12_ADDR,U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_SHIFT,U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_MASK)
#define SET_U0_DW_GMAC5_AXI64_SCFG_RAM_CFG(data)           saif_set_reg(AON_SYSCONSAIF__SYSCFG_12_ADDR,data,U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_SHIFT,U0_DW_GMAC5_AXI64_SCFG_RAM_CFG_MASK)
#define GET_U0_DW_GMAC5_AXI64_MAC_SPEED_O                  saif_get_reg(AON_SYSCONSAIF__SYSCFG_12_ADDR,U0_DW_GMAC5_AXI64_MAC_SPEED_O_SHIFT,U0_DW_GMAC5_AXI64_MAC_SPEED_O_MASK)
#define GET_U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I               saif_get_reg(AON_SYSCONSAIF__SYSCFG_12_ADDR,U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_SHIFT,U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_MASK)
#define SET_U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I(data)         saif_set_reg(AON_SYSCONSAIF__SYSCFG_12_ADDR,data,U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_SHIFT,U0_DW_GMAC5_AXI64_PHY_INTF_SEL_I_MASK)
#define GET_U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_31_0_        saif_get_reg(AON_SYSCONSAIF__SYSCFG_16_ADDR,U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_31_0__SHIFT,U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_31_0__MASK)
#define GET_U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_63_32_       saif_get_reg(AON_SYSCONSAIF__SYSCFG_20_ADDR,U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_63_32__SHIFT,U0_DW_GMAC5_AXI64_PTP_TIMESTAMP_O_63_32__MASK)
#define GET_U0_OTPC_CHIP_MODE                              saif_get_reg(AON_SYSCONSAIF__SYSCFG_24_ADDR,U0_OTPC_CHIP_MODE_SHIFT,U0_OTPC_CHIP_MODE_MASK)
#define GET_U0_OTPC_CRC_PASS                               saif_get_reg(AON_SYSCONSAIF__SYSCFG_24_ADDR,U0_OTPC_CRC_PASS_SHIFT,U0_OTPC_CRC_PASS_MASK)
#define GET_U0_OTPC_DBG_ENABLE                             saif_get_reg(AON_SYSCONSAIF__SYSCFG_24_ADDR,U0_OTPC_DBG_ENABLE_SHIFT,U0_OTPC_DBG_ENABLE_MASK)
#define GET_U0_OTPC_FL_FUNC_LOCK                           saif_get_reg(AON_SYSCONSAIF__SYSCFG_28_ADDR,U0_OTPC_FL_FUNC_LOCK_SHIFT,U0_OTPC_FL_FUNC_LOCK_MASK)
#define GET_U0_OTPC_FL_PLL0_LOCK                           saif_get_reg(AON_SYSCONSAIF__SYSCFG_32_ADDR,U0_OTPC_FL_PLL0_LOCK_SHIFT,U0_OTPC_FL_PLL0_LOCK_MASK)
#define GET_U0_OTPC_FL_PLL1_LOCK                           saif_get_reg(AON_SYSCONSAIF__SYSCFG_36_ADDR,U0_OTPC_FL_PLL1_LOCK_SHIFT,U0_OTPC_FL_PLL1_LOCK_MASK)
#define GET_U0_OTPC_FL_SEC_BOOT_LMT                        saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_OTPC_FL_SEC_BOOT_LMT_SHIFT,U0_OTPC_FL_SEC_BOOT_LMT_MASK)
#define GET_U0_OTPC_FL_XIP                                 saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_OTPC_FL_XIP_SHIFT,U0_OTPC_FL_XIP_MASK)
#define GET_U0_OTPC_LOAD_BUSY                              saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_OTPC_LOAD_BUSY_SHIFT,U0_OTPC_LOAD_BUSY_MASK)
#define GET_U0_RESET_CTRL_CLR_RESET_STATUS                 saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_RESET_CTRL_CLR_RESET_STATUS_SHIFT,U0_RESET_CTRL_CLR_RESET_STATUS_MASK)
#define SET_U0_RESET_CTRL_CLR_RESET_STATUS(data)           saif_set_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,data,U0_RESET_CTRL_CLR_RESET_STATUS_SHIFT,U0_RESET_CTRL_CLR_RESET_STATUS_MASK)
#define GET_U0_RESET_CTRL_PLL_TIMECNT_FINISH               saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_RESET_CTRL_PLL_TIMECNT_FINISH_SHIFT,U0_RESET_CTRL_PLL_TIMECNT_FINISH_MASK)
#define GET_U0_RESET_CTRL_RSTN_SW                          saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_RESET_CTRL_RSTN_SW_SHIFT,U0_RESET_CTRL_RSTN_SW_MASK)
#define SET_U0_RESET_CTRL_RSTN_SW(data)                    saif_set_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,data,U0_RESET_CTRL_RSTN_SW_SHIFT,U0_RESET_CTRL_RSTN_SW_MASK)
#define GET_U0_RESET_CTRL_SYS_RESET_STATUS                 saif_get_reg(AON_SYSCONSAIF__SYSCFG_40_ADDR,U0_RESET_CTRL_SYS_RESET_STATUS_SHIFT,U0_RESET_CTRL_SYS_RESET_STATUS_MASK)
