
#ifndef _STG_CRG_MACRO_H_
#define _STG_CRG_MACRO_H_

//#define STG_CRG_BASE_ADDR 0x0
#define CLK_U0_HIFI4_CLK_CORE_CTRL_REG_ADDR                          (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x0U)
#define CLK_U0_CDN_USB_CLK_USB_APB_CTRL_REG_ADDR                     (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x4U)
#define CLK_U0_CDN_USB_CLK_UTMI_APB_CTRL_REG_ADDR                    (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x8U)
#define CLK_U0_CDN_USB_CLK_AXI_CTRL_REG_ADDR                         (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0xCU)
#define CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR                         (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x10U)
#define CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR                         (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x14U)
#define CLK_U0_CDN_USB_CLK_APP_125_CTRL_REG_ADDR                     (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x18U)
#define CLK_U0_CDN_USB_REFCLK_CTRL_REG_ADDR                          (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x1CU)
#define CLK_U0_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR                  (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x20U)
#define CLK_U0_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR                       (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x24U)
#define CLK_U0_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR                        (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x28U)
#define CLK_U1_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR                  (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x2CU)
#define CLK_U1_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR                       (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x30U)
#define CLK_U1_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR                        (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x34U)
#define CLK_U0_PCIE01_SLV_DEC_MAINCLK_CTRL_REG_ADDR                  (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x38U)
#define CLK_U0_SEC_TOP_HCLK_CTRL_REG_ADDR                            (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x3CU)
#define CLK_U0_SEC_TOP_MISCAHB_CLK_CTRL_REG_ADDR                     (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x40U)
#define CLK_U0_STG_MTRX_GRP0_CLK_MAIN_CTRL_REG_ADDR                  (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x44U)
#define CLK_U0_STG_MTRX_GRP0_CLK_BUS_CTRL_REG_ADDR                   (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x48U)
#define CLK_U0_STG_MTRX_GRP0_CLK_STG_CTRL_REG_ADDR                   (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x4CU)
#define CLK_U0_STG_MTRX_GRP1_CLK_MAIN_CTRL_REG_ADDR                  (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x50U)
#define CLK_U0_STG_MTRX_GRP1_CLK_BUS_CTRL_REG_ADDR                   (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x54U)
#define CLK_U0_STG_MTRX_GRP1_CLK_STG_CTRL_REG_ADDR                   (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x58U)
#define CLK_U0_STG_MTRX_GRP1_CLK_HIFI_CTRL_REG_ADDR                  (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x5CU)
#define CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR                      (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x60U)
#define CLK_U0_E2_SFT7110_CLK_CORE_CTRL_REG_ADDR                     (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x64U)
#define CLK_U0_E2_SFT7110_CLK_DBG_CTRL_REG_ADDR                      (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x68U)
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_CTRL_REG_ADDR               (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x6CU)
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_CTRL_REG_ADDR               (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x70U)


#define STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR               (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x74U)

#define STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR               (U0_STG_CRG__SAIF_BD_APBS__BASE_ADDR + 0x78U)


#define CLK_U0_HIFI4_CLK_CORE_ENABLE_DATA                            1
#define CLK_U0_HIFI4_CLK_CORE_DISABLE_DATA                           0
#define CLK_U0_HIFI4_CLK_CORE_EN_SHIFT                               31
#define CLK_U0_HIFI4_CLK_CORE_EN_MASK                                0x80000000U
#define CLK_U0_CDN_USB_CLK_USB_APB_ENABLE_DATA                       1
#define CLK_U0_CDN_USB_CLK_USB_APB_DISABLE_DATA                      0
#define CLK_U0_CDN_USB_CLK_USB_APB_EN_SHIFT                          31
#define CLK_U0_CDN_USB_CLK_USB_APB_EN_MASK                           0x80000000U
#define CLK_U0_CDN_USB_CLK_UTMI_APB_ENABLE_DATA                      1
#define CLK_U0_CDN_USB_CLK_UTMI_APB_DISABLE_DATA                     0
#define CLK_U0_CDN_USB_CLK_UTMI_APB_EN_SHIFT                         31
#define CLK_U0_CDN_USB_CLK_UTMI_APB_EN_MASK                          0x80000000U
#define CLK_U0_CDN_USB_CLK_AXI_ENABLE_DATA                           1
#define CLK_U0_CDN_USB_CLK_AXI_DISABLE_DATA                          0
#define CLK_U0_CDN_USB_CLK_AXI_EN_SHIFT                              31
#define CLK_U0_CDN_USB_CLK_AXI_EN_MASK                               0x80000000U
#define CLK_U0_CDN_USB_CLK_LPM_ENABLE_DATA                           1
#define CLK_U0_CDN_USB_CLK_LPM_DISABLE_DATA                          0
#define CLK_U0_CDN_USB_CLK_LPM_EN_SHIFT                              31
#define CLK_U0_CDN_USB_CLK_LPM_EN_MASK                               0x80000000U
#define CLK_U0_CDN_USB_CLK_LPM_DIV_SHIFT                             0
#define CLK_U0_CDN_USB_CLK_LPM_DIV_MASK                              0x3U
#define CLK_U0_CDN_USB_CLK_STB_ENABLE_DATA                           1
#define CLK_U0_CDN_USB_CLK_STB_DISABLE_DATA                          0
#define CLK_U0_CDN_USB_CLK_STB_EN_SHIFT                              31
#define CLK_U0_CDN_USB_CLK_STB_EN_MASK                               0x80000000U
#define CLK_U0_CDN_USB_CLK_STB_DIV_SHIFT                             0
#define CLK_U0_CDN_USB_CLK_STB_DIV_MASK                              0x7U
#define CLK_U0_CDN_USB_CLK_APP_125_ENABLE_DATA                       1
#define CLK_U0_CDN_USB_CLK_APP_125_DISABLE_DATA                      0
#define CLK_U0_CDN_USB_CLK_APP_125_EN_SHIFT                          31
#define CLK_U0_CDN_USB_CLK_APP_125_EN_MASK                           0x80000000U
#define CLK_U0_CDN_USB_REFCLK_DIV_SHIFT                              0
#define CLK_U0_CDN_USB_REFCLK_DIV_MASK                               0x3U
#define CLK_U0_PLDA_PCIE_CLK_AXI_MST0_ENABLE_DATA                    1
#define CLK_U0_PLDA_PCIE_CLK_AXI_MST0_DISABLE_DATA                   0
#define CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT                       31
#define CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_MASK                        0x80000000U
#define CLK_U0_PLDA_PCIE_CLK_APB_ENABLE_DATA                         1
#define CLK_U0_PLDA_PCIE_CLK_APB_DISABLE_DATA                        0
#define CLK_U0_PLDA_PCIE_CLK_APB_EN_SHIFT                            31
#define CLK_U0_PLDA_PCIE_CLK_APB_EN_MASK                             0x80000000U
#define CLK_U0_PLDA_PCIE_CLK_TL_ENABLE_DATA                          1
#define CLK_U0_PLDA_PCIE_CLK_TL_DISABLE_DATA                         0
#define CLK_U0_PLDA_PCIE_CLK_TL_EN_SHIFT                             31
#define CLK_U0_PLDA_PCIE_CLK_TL_EN_MASK                              0x80000000U
#define CLK_U1_PLDA_PCIE_CLK_AXI_MST0_ENABLE_DATA                    1
#define CLK_U1_PLDA_PCIE_CLK_AXI_MST0_DISABLE_DATA                   0
#define CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT                       31
#define CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_MASK                        0x80000000U
#define CLK_U1_PLDA_PCIE_CLK_APB_ENABLE_DATA                         1
#define CLK_U1_PLDA_PCIE_CLK_APB_DISABLE_DATA                        0
#define CLK_U1_PLDA_PCIE_CLK_APB_EN_SHIFT                            31
#define CLK_U1_PLDA_PCIE_CLK_APB_EN_MASK                             0x80000000U
#define CLK_U1_PLDA_PCIE_CLK_TL_ENABLE_DATA                          1
#define CLK_U1_PLDA_PCIE_CLK_TL_DISABLE_DATA                         0
#define CLK_U1_PLDA_PCIE_CLK_TL_EN_SHIFT                             31
#define CLK_U1_PLDA_PCIE_CLK_TL_EN_MASK                              0x80000000U
#define CLK_U0_PCIE01_SLV_DEC_MAINCLK_ENABLE_DATA                    1
#define CLK_U0_PCIE01_SLV_DEC_MAINCLK_DISABLE_DATA                   0
#define CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_SHIFT                       31
#define CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_MASK                        0x80000000U
#define CLK_U0_SEC_TOP_HCLK_ENABLE_DATA                              1
#define CLK_U0_SEC_TOP_HCLK_DISABLE_DATA                             0
#define CLK_U0_SEC_TOP_HCLK_EN_SHIFT                                 31
#define CLK_U0_SEC_TOP_HCLK_EN_MASK                                  0x80000000U
#define CLK_U0_SEC_TOP_MISCAHB_CLK_ENABLE_DATA                       1
#define CLK_U0_SEC_TOP_MISCAHB_CLK_DISABLE_DATA                      0
#define CLK_U0_SEC_TOP_MISCAHB_CLK_EN_SHIFT                          31
#define CLK_U0_SEC_TOP_MISCAHB_CLK_EN_MASK                           0x80000000U
#define CLK_U0_STG_MTRX_GRP0_CLK_MAIN_ENABLE_DATA                    1
#define CLK_U0_STG_MTRX_GRP0_CLK_MAIN_DISABLE_DATA                   0
#define CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_SHIFT                       31
#define CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_MASK                        0x80000000U
#define CLK_U0_STG_MTRX_GRP0_CLK_BUS_ENABLE_DATA                     1
#define CLK_U0_STG_MTRX_GRP0_CLK_BUS_DISABLE_DATA                    0
#define CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_SHIFT                        31
#define CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_MASK                         0x80000000U
#define CLK_U0_STG_MTRX_GRP0_CLK_STG_ENABLE_DATA                     1
#define CLK_U0_STG_MTRX_GRP0_CLK_STG_DISABLE_DATA                    0
#define CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_SHIFT                        31
#define CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_MASK                         0x80000000U
#define CLK_U0_STG_MTRX_GRP1_CLK_MAIN_ENABLE_DATA                    1
#define CLK_U0_STG_MTRX_GRP1_CLK_MAIN_DISABLE_DATA                   0
#define CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_SHIFT                       31
#define CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_MASK                        0x80000000U
#define CLK_U0_STG_MTRX_GRP1_CLK_BUS_ENABLE_DATA                     1
#define CLK_U0_STG_MTRX_GRP1_CLK_BUS_DISABLE_DATA                    0
#define CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_SHIFT                        31
#define CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_MASK                         0x80000000U
#define CLK_U0_STG_MTRX_GRP1_CLK_STG_ENABLE_DATA                     1
#define CLK_U0_STG_MTRX_GRP1_CLK_STG_DISABLE_DATA                    0
#define CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_SHIFT                        31
#define CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_MASK                         0x80000000U
#define CLK_U0_STG_MTRX_GRP1_CLK_HIFI_ENABLE_DATA                    1
#define CLK_U0_STG_MTRX_GRP1_CLK_HIFI_DISABLE_DATA                   0
#define CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_SHIFT                       31
#define CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_MASK                        0x80000000U
#define CLK_U0_E2_SFT7110_RTC_CLK_ENABLE_DATA                        1
#define CLK_U0_E2_SFT7110_RTC_CLK_DISABLE_DATA                       0
#define CLK_U0_E2_SFT7110_RTC_CLK_EN_SHIFT                           31
#define CLK_U0_E2_SFT7110_RTC_CLK_EN_MASK                            0x80000000U
#define CLK_U0_E2_SFT7110_RTC_CLK_DIV_SHIFT                          0
#define CLK_U0_E2_SFT7110_RTC_CLK_DIV_MASK                           0x1FU
#define CLK_U0_E2_SFT7110_CLK_CORE_ENABLE_DATA                       1
#define CLK_U0_E2_SFT7110_CLK_CORE_DISABLE_DATA                      0
#define CLK_U0_E2_SFT7110_CLK_CORE_EN_SHIFT                          31
#define CLK_U0_E2_SFT7110_CLK_CORE_EN_MASK                           0x80000000U
#define CLK_U0_E2_SFT7110_CLK_DBG_ENABLE_DATA                        1
#define CLK_U0_E2_SFT7110_CLK_DBG_DISABLE_DATA                       0
#define CLK_U0_E2_SFT7110_CLK_DBG_EN_SHIFT                           31
#define CLK_U0_E2_SFT7110_CLK_DBG_EN_MASK                            0x80000000U
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_ENABLE_DATA                 1
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_DISABLE_DATA                0
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_SHIFT                    31
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_MASK                     0x80000000U
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_ENABLE_DATA                 1
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_DISABLE_DATA                0
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_SHIFT                    31
#define CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_MASK                     0x80000000U



#define RSTN_U0_STG_SYSCON_PRESETN_SHIFT                             0
#define RSTN_U0_STG_SYSCON_PRESETN_MASK                              (0x1 << 0)
#define RSTN_U0_STG_SYSCON_PRESETN_ASSERT                            1
#define RSTN_U0_STG_SYSCON_PRESETN_CLEAR                             0
#define RST_U0_HIFI4_RST_CORE_SHIFT                                  1
#define RST_U0_HIFI4_RST_CORE_MASK                                   (0x1 << 1)
#define RST_U0_HIFI4_RST_CORE_ASSERT                                 1
#define RST_U0_HIFI4_RST_CORE_CLEAR                                  0
#define RST_U0_HIFI4_RST_AXI_SHIFT                                   2
#define RST_U0_HIFI4_RST_AXI_MASK                                    (0x1 << 2)
#define RST_U0_HIFI4_RST_AXI_ASSERT                                  1
#define RST_U0_HIFI4_RST_AXI_CLEAR                                   0
#define RSTN_U0_SEC_TOP_HRESETN_SHIFT                                3
#define RSTN_U0_SEC_TOP_HRESETN_MASK                                 (0x1 << 3)
#define RSTN_U0_SEC_TOP_HRESETN_ASSERT                               1
#define RSTN_U0_SEC_TOP_HRESETN_CLEAR                                0
#define RST_U0_E2_SFT7110_RST_CORE_SHIFT                             4
#define RST_U0_E2_SFT7110_RST_CORE_MASK                              (0x1 << 4)
#define RST_U0_E2_SFT7110_RST_CORE_ASSERT                            1
#define RST_U0_E2_SFT7110_RST_CORE_CLEAR                             0
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_SHIFT                     5
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_MASK                      (0x1 << 5)
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_ASSERT                    1
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_CLEAR                     0
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_SHIFT                     6
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_MASK                      (0x1 << 6)
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_ASSERT                    1
#define RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_CLEAR                     0
#define RSTN_U0_CDN_USB_RSTN_AXI_SHIFT                               7
#define RSTN_U0_CDN_USB_RSTN_AXI_MASK                                (0x1 << 7)
#define RSTN_U0_CDN_USB_RSTN_AXI_ASSERT                              1
#define RSTN_U0_CDN_USB_RSTN_AXI_CLEAR                               0
#define RSTN_U0_CDN_USB_RSTN_USB_APB_SHIFT                           8
#define RSTN_U0_CDN_USB_RSTN_USB_APB_MASK                            (0x1 << 8)
#define RSTN_U0_CDN_USB_RSTN_USB_APB_ASSERT                          1
#define RSTN_U0_CDN_USB_RSTN_USB_APB_CLEAR                           0
#define RSTN_U0_CDN_USB_RSTN_UTMI_APB_SHIFT                          9
#define RSTN_U0_CDN_USB_RSTN_UTMI_APB_MASK                           (0x1 << 9)
#define RSTN_U0_CDN_USB_RSTN_UTMI_APB_ASSERT                         1
#define RSTN_U0_CDN_USB_RSTN_UTMI_APB_CLEAR                          0
#define RSTN_U0_CDN_USB_RSTN_PWRUP_SHIFT                             10
#define RSTN_U0_CDN_USB_RSTN_PWRUP_MASK                              (0x1 << 10)
#define RSTN_U0_CDN_USB_RSTN_PWRUP_ASSERT                            1
#define RSTN_U0_CDN_USB_RSTN_PWRUP_CLEAR                             0
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_SHIFT                        11
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_MASK                         (0x1 << 11)
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_ASSERT                       1
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_CLEAR                        0
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_SHIFT                        12
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_MASK                         (0x1 << 12)
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_ASSERT                       1
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_CLEAR                        0
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_SHIFT                         13
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_MASK                          (0x1 << 13)
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_ASSERT                        1
#define RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_CLEAR                         0
#define RSTN_U0_PLDA_PCIE_RSTN_BRG_SHIFT                             14
#define RSTN_U0_PLDA_PCIE_RSTN_BRG_MASK                              (0x1 << 14)
#define RSTN_U0_PLDA_PCIE_RSTN_BRG_ASSERT                            1
#define RSTN_U0_PLDA_PCIE_RSTN_BRG_CLEAR                             0
#define RSTN_U0_PLDA_PCIE_RSTN_PCIE_SHIFT                            15
#define RSTN_U0_PLDA_PCIE_RSTN_PCIE_MASK                             (0x1 << 15)
#define RSTN_U0_PLDA_PCIE_RSTN_PCIE_ASSERT                           1
#define RSTN_U0_PLDA_PCIE_RSTN_PCIE_CLEAR                            0
#define RSTN_U0_PLDA_PCIE_RSTN_APB_SHIFT                             16
#define RSTN_U0_PLDA_PCIE_RSTN_APB_MASK                              (0x1 << 16)
#define RSTN_U0_PLDA_PCIE_RSTN_APB_ASSERT                            1
#define RSTN_U0_PLDA_PCIE_RSTN_APB_CLEAR                             0
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_SHIFT                        17
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_MASK                         (0x1 << 17)
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_ASSERT                       1
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_CLEAR                        0
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_SHIFT                        18
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_MASK                         (0x1 << 18)
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_ASSERT                       1
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_CLEAR                        0
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_SHIFT                         19
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_MASK                          (0x1 << 19)
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_ASSERT                        1
#define RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_CLEAR                         0
#define RSTN_U1_PLDA_PCIE_RSTN_BRG_SHIFT                             20
#define RSTN_U1_PLDA_PCIE_RSTN_BRG_MASK                              (0x1 << 20)
#define RSTN_U1_PLDA_PCIE_RSTN_BRG_ASSERT                            1
#define RSTN_U1_PLDA_PCIE_RSTN_BRG_CLEAR                             0
#define RSTN_U1_PLDA_PCIE_RSTN_PCIE_SHIFT                            21
#define RSTN_U1_PLDA_PCIE_RSTN_PCIE_MASK                             (0x1 << 21)
#define RSTN_U1_PLDA_PCIE_RSTN_PCIE_ASSERT                           1
#define RSTN_U1_PLDA_PCIE_RSTN_PCIE_CLEAR                            0
#define RSTN_U1_PLDA_PCIE_RSTN_APB_SHIFT                             22
#define RSTN_U1_PLDA_PCIE_RSTN_APB_MASK                              (0x1 << 22)
#define RSTN_U1_PLDA_PCIE_RSTN_APB_ASSERT                            1
#define RSTN_U1_PLDA_PCIE_RSTN_APB_CLEAR                             0

#define _ENABLE_CLOCK_CLK_U0_HIFI4_CLK_CORE_ 			saif_set_reg(CLK_U0_HIFI4_CLK_CORE_CTRL_REG_ADDR, CLK_U0_HIFI4_CLK_CORE_ENABLE_DATA, CLK_U0_HIFI4_CLK_CORE_EN_SHIFT, CLK_U0_HIFI4_CLK_CORE_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_HIFI4_CLK_CORE_ 			saif_set_reg(CLK_U0_HIFI4_CLK_CORE_CTRL_REG_ADDR, CLK_U0_HIFI4_CLK_CORE_DISABLE_DATA, CLK_U0_HIFI4_CLK_CORE_EN_SHIFT, CLK_U0_HIFI4_CLK_CORE_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_HIFI4_CLK_CORE_ 		saif_get_reg(CLK_U0_HIFI4_CLK_CORE_CTRL_REG_ADDR, CLK_U0_HIFI4_CLK_CORE_EN_SHIFT, CLK_U0_HIFI4_CLK_CORE_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_HIFI4_CLK_CORE_(x) 		saif_set_reg(CLK_U0_HIFI4_CLK_CORE_CTRL_REG_ADDR, x, CLK_U0_HIFI4_CLK_CORE_EN_SHIFT, CLK_U0_HIFI4_CLK_CORE_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDN_USB_CLK_USB_APB_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_USB_APB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_USB_APB_ENABLE_DATA, CLK_U0_CDN_USB_CLK_USB_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_USB_APB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDN_USB_CLK_USB_APB_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_USB_APB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_USB_APB_DISABLE_DATA, CLK_U0_CDN_USB_CLK_USB_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_USB_APB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_USB_APB_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_USB_APB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_USB_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_USB_APB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_USB_APB_(x) 		saif_set_reg(CLK_U0_CDN_USB_CLK_USB_APB_CTRL_REG_ADDR, x, CLK_U0_CDN_USB_CLK_USB_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_USB_APB_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDN_USB_CLK_UTMI_APB_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_UTMI_APB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_UTMI_APB_ENABLE_DATA, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDN_USB_CLK_UTMI_APB_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_UTMI_APB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_UTMI_APB_DISABLE_DATA, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_UTMI_APB_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_UTMI_APB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_UTMI_APB_(x) 		saif_set_reg(CLK_U0_CDN_USB_CLK_UTMI_APB_CTRL_REG_ADDR, x, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_SHIFT, CLK_U0_CDN_USB_CLK_UTMI_APB_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDN_USB_CLK_AXI_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_AXI_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_AXI_ENABLE_DATA, CLK_U0_CDN_USB_CLK_AXI_EN_SHIFT, CLK_U0_CDN_USB_CLK_AXI_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDN_USB_CLK_AXI_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_AXI_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_AXI_DISABLE_DATA, CLK_U0_CDN_USB_CLK_AXI_EN_SHIFT, CLK_U0_CDN_USB_CLK_AXI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_AXI_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_AXI_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_AXI_EN_SHIFT, CLK_U0_CDN_USB_CLK_AXI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_AXI_(x) 		saif_set_reg(CLK_U0_CDN_USB_CLK_AXI_CTRL_REG_ADDR, x, CLK_U0_CDN_USB_CLK_AXI_EN_SHIFT, CLK_U0_CDN_USB_CLK_AXI_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDN_USB_CLK_LPM_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_LPM_ENABLE_DATA, CLK_U0_CDN_USB_CLK_LPM_EN_SHIFT, CLK_U0_CDN_USB_CLK_LPM_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDN_USB_CLK_LPM_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_LPM_DISABLE_DATA, CLK_U0_CDN_USB_CLK_LPM_EN_SHIFT, CLK_U0_CDN_USB_CLK_LPM_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_LPM_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_LPM_EN_SHIFT, CLK_U0_CDN_USB_CLK_LPM_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_LPM_(x) 		saif_set_reg(CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR, x, CLK_U0_CDN_USB_CLK_LPM_EN_SHIFT, CLK_U0_CDN_USB_CLK_LPM_EN_MASK)
#define _DIVIDE_CLOCK_CLK_U0_CDN_USB_CLK_LPM_(div) 			saif_set_reg(CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR, div, CLK_U0_CDN_USB_CLK_LPM_DIV_SHIFT, CLK_U0_CDN_USB_CLK_LPM_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_CDN_USB_CLK_LPM_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_LPM_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_LPM_DIV_SHIFT, CLK_U0_CDN_USB_CLK_LPM_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDN_USB_CLK_STB_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_STB_ENABLE_DATA, CLK_U0_CDN_USB_CLK_STB_EN_SHIFT, CLK_U0_CDN_USB_CLK_STB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDN_USB_CLK_STB_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_STB_DISABLE_DATA, CLK_U0_CDN_USB_CLK_STB_EN_SHIFT, CLK_U0_CDN_USB_CLK_STB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_STB_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_STB_EN_SHIFT, CLK_U0_CDN_USB_CLK_STB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_STB_(x) 		saif_set_reg(CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR, x, CLK_U0_CDN_USB_CLK_STB_EN_SHIFT, CLK_U0_CDN_USB_CLK_STB_EN_MASK)
#define _DIVIDE_CLOCK_CLK_U0_CDN_USB_CLK_STB_(div) 			saif_set_reg(CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR, div, CLK_U0_CDN_USB_CLK_STB_DIV_SHIFT, CLK_U0_CDN_USB_CLK_STB_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_CDN_USB_CLK_STB_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_STB_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_STB_DIV_SHIFT, CLK_U0_CDN_USB_CLK_STB_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_CDN_USB_CLK_APP_125_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_APP_125_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_APP_125_ENABLE_DATA, CLK_U0_CDN_USB_CLK_APP_125_EN_SHIFT, CLK_U0_CDN_USB_CLK_APP_125_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_CDN_USB_CLK_APP_125_ 			saif_set_reg(CLK_U0_CDN_USB_CLK_APP_125_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_APP_125_DISABLE_DATA, CLK_U0_CDN_USB_CLK_APP_125_EN_SHIFT, CLK_U0_CDN_USB_CLK_APP_125_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_APP_125_ 		saif_get_reg(CLK_U0_CDN_USB_CLK_APP_125_CTRL_REG_ADDR, CLK_U0_CDN_USB_CLK_APP_125_EN_SHIFT, CLK_U0_CDN_USB_CLK_APP_125_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_CDN_USB_CLK_APP_125_(x) 		saif_set_reg(CLK_U0_CDN_USB_CLK_APP_125_CTRL_REG_ADDR, x, CLK_U0_CDN_USB_CLK_APP_125_EN_SHIFT, CLK_U0_CDN_USB_CLK_APP_125_EN_MASK)
#define _DIVIDE_CLOCK_CLK_U0_CDN_USB_REFCLK_(div) 			saif_set_reg(CLK_U0_CDN_USB_REFCLK_CTRL_REG_ADDR, div, CLK_U0_CDN_USB_REFCLK_DIV_SHIFT, CLK_U0_CDN_USB_REFCLK_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_CDN_USB_REFCLK_ 		saif_get_reg(CLK_U0_CDN_USB_REFCLK_CTRL_REG_ADDR, CLK_U0_CDN_USB_REFCLK_DIV_SHIFT, CLK_U0_CDN_USB_REFCLK_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_PLDA_PCIE_CLK_AXI_MST0_ 			saif_set_reg(CLK_U0_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_ENABLE_DATA, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PLDA_PCIE_CLK_AXI_MST0_ 			saif_set_reg(CLK_U0_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_DISABLE_DATA, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PLDA_PCIE_CLK_AXI_MST0_ 		saif_get_reg(CLK_U0_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PLDA_PCIE_CLK_AXI_MST0_(x) 		saif_set_reg(CLK_U0_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, x, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_PLDA_PCIE_CLK_APB_ 			saif_set_reg(CLK_U0_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_APB_ENABLE_DATA, CLK_U0_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_APB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PLDA_PCIE_CLK_APB_ 			saif_set_reg(CLK_U0_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_APB_DISABLE_DATA, CLK_U0_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_APB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PLDA_PCIE_CLK_APB_ 		saif_get_reg(CLK_U0_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_APB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PLDA_PCIE_CLK_APB_(x) 		saif_set_reg(CLK_U0_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, x, CLK_U0_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_APB_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_PLDA_PCIE_CLK_TL_ 			saif_set_reg(CLK_U0_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_TL_ENABLE_DATA, CLK_U0_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_TL_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PLDA_PCIE_CLK_TL_ 			saif_set_reg(CLK_U0_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_TL_DISABLE_DATA, CLK_U0_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_TL_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PLDA_PCIE_CLK_TL_ 		saif_get_reg(CLK_U0_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, CLK_U0_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_TL_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PLDA_PCIE_CLK_TL_(x) 		saif_set_reg(CLK_U0_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, x, CLK_U0_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U0_PLDA_PCIE_CLK_TL_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_PLDA_PCIE_CLK_AXI_MST0_ 			saif_set_reg(CLK_U1_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_ENABLE_DATA, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_PLDA_PCIE_CLK_AXI_MST0_ 			saif_set_reg(CLK_U1_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_DISABLE_DATA, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_PLDA_PCIE_CLK_AXI_MST0_ 		saif_get_reg(CLK_U1_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_PLDA_PCIE_CLK_AXI_MST0_(x) 		saif_set_reg(CLK_U1_PLDA_PCIE_CLK_AXI_MST0_CTRL_REG_ADDR, x, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_AXI_MST0_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_PLDA_PCIE_CLK_APB_ 			saif_set_reg(CLK_U1_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_APB_ENABLE_DATA, CLK_U1_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_APB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_PLDA_PCIE_CLK_APB_ 			saif_set_reg(CLK_U1_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_APB_DISABLE_DATA, CLK_U1_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_APB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_PLDA_PCIE_CLK_APB_ 		saif_get_reg(CLK_U1_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_APB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_PLDA_PCIE_CLK_APB_(x) 		saif_set_reg(CLK_U1_PLDA_PCIE_CLK_APB_CTRL_REG_ADDR, x, CLK_U1_PLDA_PCIE_CLK_APB_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_APB_EN_MASK)
#define _ENABLE_CLOCK_CLK_U1_PLDA_PCIE_CLK_TL_ 			saif_set_reg(CLK_U1_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_TL_ENABLE_DATA, CLK_U1_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_TL_EN_MASK)
#define _DISABLE_CLOCK_CLK_U1_PLDA_PCIE_CLK_TL_ 			saif_set_reg(CLK_U1_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_TL_DISABLE_DATA, CLK_U1_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_TL_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U1_PLDA_PCIE_CLK_TL_ 		saif_get_reg(CLK_U1_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, CLK_U1_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_TL_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U1_PLDA_PCIE_CLK_TL_(x) 		saif_set_reg(CLK_U1_PLDA_PCIE_CLK_TL_CTRL_REG_ADDR, x, CLK_U1_PLDA_PCIE_CLK_TL_EN_SHIFT, CLK_U1_PLDA_PCIE_CLK_TL_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_PCIE01_SLV_DEC_MAINCLK_ 			saif_set_reg(CLK_U0_PCIE01_SLV_DEC_MAINCLK_CTRL_REG_ADDR, CLK_U0_PCIE01_SLV_DEC_MAINCLK_ENABLE_DATA, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_SHIFT, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_PCIE01_SLV_DEC_MAINCLK_ 			saif_set_reg(CLK_U0_PCIE01_SLV_DEC_MAINCLK_CTRL_REG_ADDR, CLK_U0_PCIE01_SLV_DEC_MAINCLK_DISABLE_DATA, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_SHIFT, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_PCIE01_SLV_DEC_MAINCLK_ 		saif_get_reg(CLK_U0_PCIE01_SLV_DEC_MAINCLK_CTRL_REG_ADDR, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_SHIFT, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_PCIE01_SLV_DEC_MAINCLK_(x) 		saif_set_reg(CLK_U0_PCIE01_SLV_DEC_MAINCLK_CTRL_REG_ADDR, x, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_SHIFT, CLK_U0_PCIE01_SLV_DEC_MAINCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_SEC_TOP_HCLK_ 			saif_set_reg(CLK_U0_SEC_TOP_HCLK_CTRL_REG_ADDR, CLK_U0_SEC_TOP_HCLK_ENABLE_DATA, CLK_U0_SEC_TOP_HCLK_EN_SHIFT, CLK_U0_SEC_TOP_HCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_SEC_TOP_HCLK_ 			saif_set_reg(CLK_U0_SEC_TOP_HCLK_CTRL_REG_ADDR, CLK_U0_SEC_TOP_HCLK_DISABLE_DATA, CLK_U0_SEC_TOP_HCLK_EN_SHIFT, CLK_U0_SEC_TOP_HCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_SEC_TOP_HCLK_ 		saif_get_reg(CLK_U0_SEC_TOP_HCLK_CTRL_REG_ADDR, CLK_U0_SEC_TOP_HCLK_EN_SHIFT, CLK_U0_SEC_TOP_HCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_SEC_TOP_HCLK_(x) 		saif_set_reg(CLK_U0_SEC_TOP_HCLK_CTRL_REG_ADDR, x, CLK_U0_SEC_TOP_HCLK_EN_SHIFT, CLK_U0_SEC_TOP_HCLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_SEC_TOP_MISCAHB_CLK_ 			saif_set_reg(CLK_U0_SEC_TOP_MISCAHB_CLK_CTRL_REG_ADDR, CLK_U0_SEC_TOP_MISCAHB_CLK_ENABLE_DATA, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_SHIFT, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_SEC_TOP_MISCAHB_CLK_ 			saif_set_reg(CLK_U0_SEC_TOP_MISCAHB_CLK_CTRL_REG_ADDR, CLK_U0_SEC_TOP_MISCAHB_CLK_DISABLE_DATA, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_SHIFT, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_SEC_TOP_MISCAHB_CLK_ 		saif_get_reg(CLK_U0_SEC_TOP_MISCAHB_CLK_CTRL_REG_ADDR, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_SHIFT, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_SEC_TOP_MISCAHB_CLK_(x) 		saif_set_reg(CLK_U0_SEC_TOP_MISCAHB_CLK_CTRL_REG_ADDR, x, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_SHIFT, CLK_U0_SEC_TOP_MISCAHB_CLK_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP0_CLK_MAIN_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_MAIN_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_ENABLE_DATA, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP0_CLK_MAIN_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_MAIN_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_DISABLE_DATA, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP0_CLK_MAIN_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP0_CLK_MAIN_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP0_CLK_MAIN_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_MAIN_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_MAIN_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP0_CLK_BUS_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_BUS_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_BUS_ENABLE_DATA, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP0_CLK_BUS_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_BUS_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_BUS_DISABLE_DATA, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP0_CLK_BUS_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP0_CLK_BUS_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP0_CLK_BUS_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_BUS_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_BUS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP0_CLK_STG_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_STG_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_STG_ENABLE_DATA, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP0_CLK_STG_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_STG_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_STG_DISABLE_DATA, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP0_CLK_STG_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP0_CLK_STG_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP0_CLK_STG_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP0_CLK_STG_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP0_CLK_STG_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_MAIN_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_MAIN_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_ENABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_MAIN_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_MAIN_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_DISABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_MAIN_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP1_CLK_MAIN_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_MAIN_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_MAIN_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_MAIN_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_BUS_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_BUS_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_BUS_ENABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_BUS_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_BUS_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_BUS_DISABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_BUS_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP1_CLK_BUS_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_BUS_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_BUS_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_BUS_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_STG_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_STG_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_STG_ENABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_STG_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_STG_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_STG_DISABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_STG_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP1_CLK_STG_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_STG_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_STG_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_STG_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_HIFI_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_HIFI_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_ENABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_STG_MTRX_GRP1_CLK_HIFI_ 			saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_HIFI_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_DISABLE_DATA, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_HIFI_ 		saif_get_reg(CLK_U0_STG_MTRX_GRP1_CLK_HIFI_CTRL_REG_ADDR, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_STG_MTRX_GRP1_CLK_HIFI_(x) 		saif_set_reg(CLK_U0_STG_MTRX_GRP1_CLK_HIFI_CTRL_REG_ADDR, x, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_SHIFT, CLK_U0_STG_MTRX_GRP1_CLK_HIFI_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_E2_SFT7110_RTC_CLK_ 			saif_set_reg(CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_RTC_CLK_ENABLE_DATA, CLK_U0_E2_SFT7110_RTC_CLK_EN_SHIFT, CLK_U0_E2_SFT7110_RTC_CLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_E2_SFT7110_RTC_CLK_ 			saif_set_reg(CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_RTC_CLK_DISABLE_DATA, CLK_U0_E2_SFT7110_RTC_CLK_EN_SHIFT, CLK_U0_E2_SFT7110_RTC_CLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_E2_SFT7110_RTC_CLK_ 		saif_get_reg(CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_RTC_CLK_EN_SHIFT, CLK_U0_E2_SFT7110_RTC_CLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_E2_SFT7110_RTC_CLK_(x) 		saif_set_reg(CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR, x, CLK_U0_E2_SFT7110_RTC_CLK_EN_SHIFT, CLK_U0_E2_SFT7110_RTC_CLK_EN_MASK)
#define _DIVIDE_CLOCK_CLK_U0_E2_SFT7110_RTC_CLK_(div) 			saif_set_reg(CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR, div, CLK_U0_E2_SFT7110_RTC_CLK_DIV_SHIFT, CLK_U0_E2_SFT7110_RTC_CLK_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_E2_SFT7110_RTC_CLK_ 		saif_get_reg(CLK_U0_E2_SFT7110_RTC_CLK_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_RTC_CLK_DIV_SHIFT, CLK_U0_E2_SFT7110_RTC_CLK_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_E2_SFT7110_CLK_CORE_ 			saif_set_reg(CLK_U0_E2_SFT7110_CLK_CORE_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_CLK_CORE_ENABLE_DATA, CLK_U0_E2_SFT7110_CLK_CORE_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_CORE_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_E2_SFT7110_CLK_CORE_ 			saif_set_reg(CLK_U0_E2_SFT7110_CLK_CORE_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_CLK_CORE_DISABLE_DATA, CLK_U0_E2_SFT7110_CLK_CORE_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_CORE_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_E2_SFT7110_CLK_CORE_ 		saif_get_reg(CLK_U0_E2_SFT7110_CLK_CORE_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_CLK_CORE_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_CORE_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_E2_SFT7110_CLK_CORE_(x) 		saif_set_reg(CLK_U0_E2_SFT7110_CLK_CORE_CTRL_REG_ADDR, x, CLK_U0_E2_SFT7110_CLK_CORE_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_CORE_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_E2_SFT7110_CLK_DBG_ 			saif_set_reg(CLK_U0_E2_SFT7110_CLK_DBG_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_CLK_DBG_ENABLE_DATA, CLK_U0_E2_SFT7110_CLK_DBG_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_DBG_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_E2_SFT7110_CLK_DBG_ 			saif_set_reg(CLK_U0_E2_SFT7110_CLK_DBG_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_CLK_DBG_DISABLE_DATA, CLK_U0_E2_SFT7110_CLK_DBG_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_DBG_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_E2_SFT7110_CLK_DBG_ 		saif_get_reg(CLK_U0_E2_SFT7110_CLK_DBG_CTRL_REG_ADDR, CLK_U0_E2_SFT7110_CLK_DBG_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_DBG_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_E2_SFT7110_CLK_DBG_(x) 		saif_set_reg(CLK_U0_E2_SFT7110_CLK_DBG_CTRL_REG_ADDR, x, CLK_U0_E2_SFT7110_CLK_DBG_EN_SHIFT, CLK_U0_E2_SFT7110_CLK_DBG_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_ 			saif_set_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_CTRL_REG_ADDR, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_ENABLE_DATA, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_ 			saif_set_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_CTRL_REG_ADDR, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_DISABLE_DATA, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_ 		saif_get_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_CTRL_REG_ADDR, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_(x) 		saif_set_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_CTRL_REG_ADDR, x, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AXI_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_ 			saif_set_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_CTRL_REG_ADDR, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_ENABLE_DATA, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_ 			saif_set_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_CTRL_REG_ADDR, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_DISABLE_DATA, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_ 		saif_get_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_CTRL_REG_ADDR, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_(x) 		saif_set_reg(CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_CTRL_REG_ADDR, x, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_SHIFT, CLK_U0_DW_DMA1P_8CH_56HS_CLK_AHB_EN_MASK)


#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_STG_SYSCON_PRESETN_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_STG_SYSCON_PRESETN_SHIFT, RSTN_U0_STG_SYSCON_PRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_STG_SYSCON_PRESETN_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_STG_SYSCON_PRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_STG_SYSCON_PRESETN_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_STG_SYSCON_PRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RST_U0_HIFI4_RST_CORE_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_HIFI4_RST_CORE_SHIFT, RST_U0_HIFI4_RST_CORE_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_HIFI4_RST_CORE_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_HIFI4_RST_CORE_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_HIFI4_RST_CORE_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_HIFI4_RST_CORE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RST_U0_HIFI4_RST_AXI_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_HIFI4_RST_AXI_SHIFT, RST_U0_HIFI4_RST_AXI_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_HIFI4_RST_AXI_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_HIFI4_RST_AXI_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_HIFI4_RST_AXI_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_HIFI4_RST_AXI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_SEC_TOP_HRESETN_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SEC_TOP_HRESETN_SHIFT, RSTN_U0_SEC_TOP_HRESETN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_SEC_TOP_HRESETN_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SEC_TOP_HRESETN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_SEC_TOP_HRESETN_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_SEC_TOP_HRESETN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RST_U0_E2_SFT7110_RST_CORE_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_E2_SFT7110_RST_CORE_SHIFT, RST_U0_E2_SFT7110_RST_CORE_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_E2_SFT7110_RST_CORE_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_E2_SFT7110_RST_CORE_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_E2_SFT7110_RST_CORE_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_E2_SFT7110_RST_CORE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_SHIFT, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AXI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_SHIFT, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_DW_DMA1P_8CH_56HS_RSTN_AHB_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDN_USB_RSTN_AXI_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_AXI_SHIFT, RSTN_U0_CDN_USB_RSTN_AXI_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_AXI_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_AXI_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_AXI_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_AXI_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDN_USB_RSTN_USB_APB_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_USB_APB_SHIFT, RSTN_U0_CDN_USB_RSTN_USB_APB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_USB_APB_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_USB_APB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_USB_APB_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_USB_APB_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDN_USB_RSTN_UTMI_APB_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_UTMI_APB_SHIFT, RSTN_U0_CDN_USB_RSTN_UTMI_APB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_UTMI_APB_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_UTMI_APB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_UTMI_APB_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_UTMI_APB_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_CDN_USB_RSTN_PWRUP_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_PWRUP_SHIFT, RSTN_U0_CDN_USB_RSTN_PWRUP_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_PWRUP_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_PWRUP_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_CDN_USB_RSTN_PWRUP_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_CDN_USB_RSTN_PWRUP_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_SHIFT, RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_MST0_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_SHIFT, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV0_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_SHIFT, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_AXI_SLV_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_BRG_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_BRG_SHIFT, RSTN_U0_PLDA_PCIE_RSTN_BRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_BRG_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_BRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_BRG_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_BRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_PCIE_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_PCIE_SHIFT, RSTN_U0_PLDA_PCIE_RSTN_PCIE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_PCIE_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_PCIE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_PCIE_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_PCIE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_APB_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_APB_SHIFT, RSTN_U0_PLDA_PCIE_RSTN_APB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_APB_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_APB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_PLDA_PCIE_RSTN_APB_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_PLDA_PCIE_RSTN_APB_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_SHIFT, RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_MST0_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_SHIFT, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV0_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_SHIFT, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_AXI_SLV_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_BRG_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_BRG_SHIFT, RSTN_U1_PLDA_PCIE_RSTN_BRG_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_BRG_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_BRG_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_BRG_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_BRG_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_PCIE_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_PCIE_SHIFT, RSTN_U1_PLDA_PCIE_RSTN_PCIE_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_PCIE_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_PCIE_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_PCIE_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_PCIE_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_APB_ 	saif_get_reg(STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_APB_SHIFT, RSTN_U1_PLDA_PCIE_RSTN_APB_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_APB_ 	saif_assert_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_APB_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U1_PLDA_PCIE_RSTN_APB_ 	saif_clear_rst(STG_CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, STG_CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U1_PLDA_PCIE_RSTN_APB_MASK)


#endif //_STG_CRG_MACRO_H_
