
#ifndef _CRG_MACRO_H_
#define _CRG_MACRO_H_

//#define CRG_BASE_ADDR 0x0
#define CLK_DOM4_APB_FUNC_CTRL_REG_ADDR                              (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x0U)
#define CLK_MIPI_RX0_PXL_CTRL_REG_ADDR                               (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x4U)
#define CLK_DVP_INV_CTRL_REG_ADDR                                    (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x8U)
#define CLK_U0_M31DPHY_CFGCLK_IN_CTRL_REG_ADDR                       (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0xCU)
#define CLK_U0_M31DPHY_REFCLK_IN_CTRL_REG_ADDR                       (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x10U)
#define CLK_U0_M31DPHY_TXCLKESC_LAN0_CTRL_REG_ADDR                   (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x14U)
#define CLK_U0_VIN_PCLK_CTRL_REG_ADDR                                (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x18U)
#define CLK_U0_VIN_SYS_CLK_CTRL_REG_ADDR                             (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x1CU)
#define CLK_U0_VIN_PIXEL_CLK_IF0_CTRL_REG_ADDR                       (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x20U)
#define CLK_U0_VIN_PIXEL_CLK_IF1_CTRL_REG_ADDR                       (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x24U)
#define CLK_U0_VIN_PIXEL_CLK_IF2_CTRL_REG_ADDR                       (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x28U)
#define CLK_U0_VIN_PIXEL_CLK_IF3_CTRL_REG_ADDR                       (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x2CU)
#define CLK_U0_VIN_CLK_P_AXIWR_CTRL_REG_ADDR                         (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x30U)
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR                 (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x34U)


#define CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR                   (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x38U)

#define CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR                   (U0_CRG__SAIF_BD_APB__BASE_ADDR + 0x3CU)


#define CLK_DOM4_APB_FUNC_DIV_SHIFT                                  0
#define CLK_DOM4_APB_FUNC_DIV_MASK                                   0xFU
#define CLK_MIPI_RX0_PXL_DIV_SHIFT                                   0
#define CLK_MIPI_RX0_PXL_DIV_MASK                                    0xFU
#define CLK_DVP_INV_POLARITY_DATA                                    1
#define CLK_DVP_INV_UN_POLARITY_DATA                                 0
#define CLK_DVP_INV_POLARITY_SHIFT                                   30
#define CLK_DVP_INV_POLARITY_MASK                                    0x40000000U
#define CLK_U0_M31DPHY_CFGCLK_IN_DIV_SHIFT                           0
#define CLK_U0_M31DPHY_CFGCLK_IN_DIV_MASK                            0x1FU
#define CLK_U0_M31DPHY_REFCLK_IN_DIV_SHIFT                           0
#define CLK_U0_M31DPHY_REFCLK_IN_DIV_MASK                            0x1FU
#define CLK_U0_M31DPHY_TXCLKESC_LAN0_DIV_SHIFT                       0
#define CLK_U0_M31DPHY_TXCLKESC_LAN0_DIV_MASK                        0x3FU
#define CLK_U0_VIN_PCLK_ENABLE_DATA                                  1
#define CLK_U0_VIN_PCLK_DISABLE_DATA                                 0
#define CLK_U0_VIN_PCLK_EN_SHIFT                                     31
#define CLK_U0_VIN_PCLK_EN_MASK                                      0x80000000U
#define CLK_U0_VIN_SYS_CLK_DIV_SHIFT                                 0
#define CLK_U0_VIN_SYS_CLK_DIV_MASK                                  0xFU
#define CLK_U0_VIN_PIXEL_CLK_IF0_ENABLE_DATA                         1
#define CLK_U0_VIN_PIXEL_CLK_IF0_DISABLE_DATA                        0
#define CLK_U0_VIN_PIXEL_CLK_IF0_EN_SHIFT                            31
#define CLK_U0_VIN_PIXEL_CLK_IF0_EN_MASK                             0x80000000U
#define CLK_U0_VIN_PIXEL_CLK_IF1_ENABLE_DATA                         1
#define CLK_U0_VIN_PIXEL_CLK_IF1_DISABLE_DATA                        0
#define CLK_U0_VIN_PIXEL_CLK_IF1_EN_SHIFT                            31
#define CLK_U0_VIN_PIXEL_CLK_IF1_EN_MASK                             0x80000000U
#define CLK_U0_VIN_PIXEL_CLK_IF2_ENABLE_DATA                         1
#define CLK_U0_VIN_PIXEL_CLK_IF2_DISABLE_DATA                        0
#define CLK_U0_VIN_PIXEL_CLK_IF2_EN_SHIFT                            31
#define CLK_U0_VIN_PIXEL_CLK_IF2_EN_MASK                             0x80000000U
#define CLK_U0_VIN_PIXEL_CLK_IF3_ENABLE_DATA                         1
#define CLK_U0_VIN_PIXEL_CLK_IF3_DISABLE_DATA                        0
#define CLK_U0_VIN_PIXEL_CLK_IF3_EN_SHIFT                            31
#define CLK_U0_VIN_PIXEL_CLK_IF3_EN_MASK                             0x80000000U
#define CLK_U0_VIN_CLK_P_AXIWR_SW_SHIFT                              24
#define CLK_U0_VIN_CLK_P_AXIWR_SW_MASK                               0x1000000U
#define CLK_U0_VIN_CLK_P_AXIWR_SW_CLK_MIPI_RX0_PXL_DATA              0
#define CLK_U0_VIN_CLK_P_AXIWR_SW_CLK_DVP_INV_DATA                   1
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_ENABLE_DATA                   1
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_DISABLE_DATA                  0
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_SHIFT                      31
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_MASK                       0x80000000U
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_SHIFT                      24
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_MASK                       0x1000000U
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_CLK_MIPI_RX0_PXL_DATA      0
#define CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_CLK_DVP_INV_DATA           1



#define RST_U0_ISPV2_TOP_WRAPPER_RST_P_SHIFT                         0
#define RST_U0_ISPV2_TOP_WRAPPER_RST_P_MASK                          (0x1 << 0)
#define RST_U0_ISPV2_TOP_WRAPPER_RST_P_ASSERT                        1
#define RST_U0_ISPV2_TOP_WRAPPER_RST_P_CLEAR                         0
#define RST_U0_ISPV2_TOP_WRAPPER_RST_C_SHIFT                         1
#define RST_U0_ISPV2_TOP_WRAPPER_RST_C_MASK                          (0x1 << 1)
#define RST_U0_ISPV2_TOP_WRAPPER_RST_C_ASSERT                        1
#define RST_U0_ISPV2_TOP_WRAPPER_RST_C_CLEAR                         0
#define RSTN_U0_M31DPHY_HW_RSTN_SHIFT                                2
#define RSTN_U0_M31DPHY_HW_RSTN_MASK                                 (0x1 << 2)
#define RSTN_U0_M31DPHY_HW_RSTN_ASSERT                               1
#define RSTN_U0_M31DPHY_HW_RSTN_CLEAR                                0
#define RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_SHIFT                       3
#define RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_MASK                        (0x1 << 3)
#define RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_ASSERT                      1
#define RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_CLEAR                       0
#define RSTN_U0_VIN_RST_N_PCLK_SHIFT                                 4
#define RSTN_U0_VIN_RST_N_PCLK_MASK                                  (0x1 << 4)
#define RSTN_U0_VIN_RST_N_PCLK_ASSERT                                1
#define RSTN_U0_VIN_RST_N_PCLK_CLEAR                                 0
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_SHIFT                        5
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_MASK                         (0x1 << 5)
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_ASSERT                       1
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_CLEAR                        0
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_SHIFT                        6
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_MASK                         (0x1 << 6)
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_ASSERT                       1
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_CLEAR                        0
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_SHIFT                        7
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_MASK                         (0x1 << 7)
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_ASSERT                       1
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_CLEAR                        0
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_SHIFT                        8
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_MASK                         (0x1 << 8)
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_ASSERT                       1
#define RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_CLEAR                        0
#define RSTN_U0_VIN_RST_N_SYS_CLK_SHIFT                              9
#define RSTN_U0_VIN_RST_N_SYS_CLK_MASK                               (0x1 << 9)
#define RSTN_U0_VIN_RST_N_SYS_CLK_ASSERT                             1
#define RSTN_U0_VIN_RST_N_SYS_CLK_CLEAR                              0
#define RSTN_U0_VIN_RST_P_AXIRD_SHIFT                                10
#define RSTN_U0_VIN_RST_P_AXIRD_MASK                                 (0x1 << 10)
#define RSTN_U0_VIN_RST_P_AXIRD_ASSERT                               1
#define RSTN_U0_VIN_RST_P_AXIRD_CLEAR                                0
#define RSTN_U0_VIN_RST_P_AXIWR_SHIFT                                11
#define RSTN_U0_VIN_RST_P_AXIWR_MASK                                 (0x1 << 11)
#define RSTN_U0_VIN_RST_P_AXIWR_ASSERT                               1
#define RSTN_U0_VIN_RST_P_AXIWR_CLEAR                                0

#define _DIVIDE_CLOCK_CLK_DOM4_APB_FUNC_(div) 			saif_set_reg(CLK_DOM4_APB_FUNC_CTRL_REG_ADDR, div, CLK_DOM4_APB_FUNC_DIV_SHIFT, CLK_DOM4_APB_FUNC_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_DOM4_APB_FUNC_ 		saif_get_reg(CLK_DOM4_APB_FUNC_CTRL_REG_ADDR, CLK_DOM4_APB_FUNC_DIV_SHIFT, CLK_DOM4_APB_FUNC_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_MIPI_RX0_PXL_(div) 			saif_set_reg(CLK_MIPI_RX0_PXL_CTRL_REG_ADDR, div, CLK_MIPI_RX0_PXL_DIV_SHIFT, CLK_MIPI_RX0_PXL_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_MIPI_RX0_PXL_ 		saif_get_reg(CLK_MIPI_RX0_PXL_CTRL_REG_ADDR, CLK_MIPI_RX0_PXL_DIV_SHIFT, CLK_MIPI_RX0_PXL_DIV_MASK)
#define _SET_CLOCK_CLK_DVP_INV_POLARITY_ 		saif_set_reg(CLK_DVP_INV_CTRL_REG_ADDR, CLK_DVP_INV_POLARITY_DATA, CLK_DVP_INV_POLARITY_SHIFT, CLK_DVP_INV_POLARITY_MASK)
#define _UNSET_CLOCK_CLK_DVP_INV_POLARITY_ 		saif_set_reg(CLK_DVP_INV_CTRL_REG_ADDR, CLK_DVP_INV_UN_POLARITY_DATA, CLK_DVP_INV_POLARITY_SHIFT, CLK_DVP_INV_POLARITY_MASK)
#define _GET_CLOCK_POLARITY_STATUS_CLK_DVP_INV_ 		saif_get_reg(CLK_DVP_INV_CTRL_REG_ADDR, CLK_DVP_INV_POLARITY_SHIFT, CLK_DVP_INV_POLARITY_MASK)
#define _SET_CLOCK_POLARITY_STATUS_CLK_DVP_INV_(x) 		saif_set_reg(CLK_DVP_INV_CTRL_REG_ADDR, x, CLK_DVP_INV_POLARITY_SHIFT, CLK_DVP_INV_POLARITY_MASK)
#define _DIVIDE_CLOCK_CLK_U0_M31DPHY_CFGCLK_IN_(div) 			saif_set_reg(CLK_U0_M31DPHY_CFGCLK_IN_CTRL_REG_ADDR, div, CLK_U0_M31DPHY_CFGCLK_IN_DIV_SHIFT, CLK_U0_M31DPHY_CFGCLK_IN_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_M31DPHY_CFGCLK_IN_ 		saif_get_reg(CLK_U0_M31DPHY_CFGCLK_IN_CTRL_REG_ADDR, CLK_U0_M31DPHY_CFGCLK_IN_DIV_SHIFT, CLK_U0_M31DPHY_CFGCLK_IN_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_U0_M31DPHY_REFCLK_IN_(div) 			saif_set_reg(CLK_U0_M31DPHY_REFCLK_IN_CTRL_REG_ADDR, div, CLK_U0_M31DPHY_REFCLK_IN_DIV_SHIFT, CLK_U0_M31DPHY_REFCLK_IN_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_M31DPHY_REFCLK_IN_ 		saif_get_reg(CLK_U0_M31DPHY_REFCLK_IN_CTRL_REG_ADDR, CLK_U0_M31DPHY_REFCLK_IN_DIV_SHIFT, CLK_U0_M31DPHY_REFCLK_IN_DIV_MASK)
#define _DIVIDE_CLOCK_CLK_U0_M31DPHY_TXCLKESC_LAN0_(div) 			saif_set_reg(CLK_U0_M31DPHY_TXCLKESC_LAN0_CTRL_REG_ADDR, div, CLK_U0_M31DPHY_TXCLKESC_LAN0_DIV_SHIFT, CLK_U0_M31DPHY_TXCLKESC_LAN0_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_M31DPHY_TXCLKESC_LAN0_ 		saif_get_reg(CLK_U0_M31DPHY_TXCLKESC_LAN0_CTRL_REG_ADDR, CLK_U0_M31DPHY_TXCLKESC_LAN0_DIV_SHIFT, CLK_U0_M31DPHY_TXCLKESC_LAN0_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_VIN_PCLK_ 			saif_set_reg(CLK_U0_VIN_PCLK_CTRL_REG_ADDR, CLK_U0_VIN_PCLK_ENABLE_DATA, CLK_U0_VIN_PCLK_EN_SHIFT, CLK_U0_VIN_PCLK_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_VIN_PCLK_ 			saif_set_reg(CLK_U0_VIN_PCLK_CTRL_REG_ADDR, CLK_U0_VIN_PCLK_DISABLE_DATA, CLK_U0_VIN_PCLK_EN_SHIFT, CLK_U0_VIN_PCLK_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PCLK_ 		saif_get_reg(CLK_U0_VIN_PCLK_CTRL_REG_ADDR, CLK_U0_VIN_PCLK_EN_SHIFT, CLK_U0_VIN_PCLK_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PCLK_(x) 		saif_set_reg(CLK_U0_VIN_PCLK_CTRL_REG_ADDR, x, CLK_U0_VIN_PCLK_EN_SHIFT, CLK_U0_VIN_PCLK_EN_MASK)
#define _DIVIDE_CLOCK_CLK_U0_VIN_SYS_CLK_(div) 			saif_set_reg(CLK_U0_VIN_SYS_CLK_CTRL_REG_ADDR, div, CLK_U0_VIN_SYS_CLK_DIV_SHIFT, CLK_U0_VIN_SYS_CLK_DIV_MASK)
#define _GET_CLOCK_DIVIDE_STATUS_CLK_U0_VIN_SYS_CLK_ 		saif_get_reg(CLK_U0_VIN_SYS_CLK_CTRL_REG_ADDR, CLK_U0_VIN_SYS_CLK_DIV_SHIFT, CLK_U0_VIN_SYS_CLK_DIV_MASK)
#define _ENABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF0_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF0_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF0_ENABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF0_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF0_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF0_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF0_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF0_DISABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF0_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF0_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF0_ 		saif_get_reg(CLK_U0_VIN_PIXEL_CLK_IF0_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF0_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF0_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF0_(x) 		saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF0_CTRL_REG_ADDR, x, CLK_U0_VIN_PIXEL_CLK_IF0_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF0_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF1_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF1_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF1_ENABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF1_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF1_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF1_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF1_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF1_DISABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF1_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF1_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF1_ 		saif_get_reg(CLK_U0_VIN_PIXEL_CLK_IF1_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF1_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF1_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF1_(x) 		saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF1_CTRL_REG_ADDR, x, CLK_U0_VIN_PIXEL_CLK_IF1_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF1_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF2_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF2_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF2_ENABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF2_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF2_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF2_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF2_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF2_DISABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF2_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF2_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF2_ 		saif_get_reg(CLK_U0_VIN_PIXEL_CLK_IF2_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF2_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF2_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF2_(x) 		saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF2_CTRL_REG_ADDR, x, CLK_U0_VIN_PIXEL_CLK_IF2_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF2_EN_MASK)
#define _ENABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF3_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF3_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF3_ENABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF3_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF3_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_VIN_PIXEL_CLK_IF3_ 			saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF3_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF3_DISABLE_DATA, CLK_U0_VIN_PIXEL_CLK_IF3_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF3_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF3_ 		saif_get_reg(CLK_U0_VIN_PIXEL_CLK_IF3_CTRL_REG_ADDR, CLK_U0_VIN_PIXEL_CLK_IF3_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF3_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_VIN_PIXEL_CLK_IF3_(x) 		saif_set_reg(CLK_U0_VIN_PIXEL_CLK_IF3_CTRL_REG_ADDR, x, CLK_U0_VIN_PIXEL_CLK_IF3_EN_SHIFT, CLK_U0_VIN_PIXEL_CLK_IF3_EN_MASK)
#define _SWITCH_CLOCK_CLK_U0_VIN_CLK_P_AXIWR_SOURCE_CLK_MIPI_RX0_PXL_ 	saif_set_reg(CLK_U0_VIN_CLK_P_AXIWR_CTRL_REG_ADDR, CLK_U0_VIN_CLK_P_AXIWR_SW_CLK_MIPI_RX0_PXL_DATA, CLK_U0_VIN_CLK_P_AXIWR_SW_SHIFT, CLK_U0_VIN_CLK_P_AXIWR_SW_MASK)
#define _SWITCH_CLOCK_CLK_U0_VIN_CLK_P_AXIWR_SOURCE_CLK_DVP_INV_ 	saif_set_reg(CLK_U0_VIN_CLK_P_AXIWR_CTRL_REG_ADDR, CLK_U0_VIN_CLK_P_AXIWR_SW_CLK_DVP_INV_DATA, CLK_U0_VIN_CLK_P_AXIWR_SW_SHIFT, CLK_U0_VIN_CLK_P_AXIWR_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_U0_VIN_CLK_P_AXIWR_ 		saif_get_reg(CLK_U0_VIN_CLK_P_AXIWR_CTRL_REG_ADDR, CLK_U0_VIN_CLK_P_AXIWR_SW_SHIFT, CLK_U0_VIN_CLK_P_AXIWR_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_U0_VIN_CLK_P_AXIWR_(x) 		saif_set_reg(CLK_U0_VIN_CLK_P_AXIWR_CTRL_REG_ADDR, x, CLK_U0_VIN_CLK_P_AXIWR_SW_SHIFT, CLK_U0_VIN_CLK_P_AXIWR_SW_MASK)
#define _ENABLE_CLOCK_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_ 			saif_set_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_ENABLE_DATA, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_MASK)
#define _DISABLE_CLOCK_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_ 			saif_set_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_DISABLE_DATA, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_MASK)
#define _GET_CLOCK_ENABLE_STATUS_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_ 		saif_get_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_MASK)
#define _SET_CLOCK_ENABLE_STATUS_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_(x) 		saif_set_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, x, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_EN_MASK)
#define _SWITCH_CLOCK_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SOURCE_CLK_MIPI_RX0_PXL_ 	saif_set_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_CLK_MIPI_RX0_PXL_DATA, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_MASK)
#define _SWITCH_CLOCK_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SOURCE_CLK_DVP_INV_ 	saif_set_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_CLK_DVP_INV_DATA, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_MASK)
#define _GET_CLOCK_SOURCE_STATUS_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_ 		saif_get_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_MASK)
#define _SET_CLOCK_SOURCE_STATUS_CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_(x) 		saif_set_reg(CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_CTRL_REG_ADDR, x, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_SHIFT, CLK_U0_ISPV2_TOP_WRAPPER_CLK_C_SW_MASK)


#define _READ_RESET_STATUS_RSTGEN_RST_U0_ISPV2_TOP_WRAPPER_RST_P_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_ISPV2_TOP_WRAPPER_RST_P_SHIFT, RST_U0_ISPV2_TOP_WRAPPER_RST_P_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_ISPV2_TOP_WRAPPER_RST_P_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_ISPV2_TOP_WRAPPER_RST_P_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_ISPV2_TOP_WRAPPER_RST_P_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_ISPV2_TOP_WRAPPER_RST_P_MASK)
#define _READ_RESET_STATUS_RSTGEN_RST_U0_ISPV2_TOP_WRAPPER_RST_C_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_ISPV2_TOP_WRAPPER_RST_C_SHIFT, RST_U0_ISPV2_TOP_WRAPPER_RST_C_MASK)
#define _ASSERT_RESET_RSTGEN_RST_U0_ISPV2_TOP_WRAPPER_RST_C_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_ISPV2_TOP_WRAPPER_RST_C_MASK)
#define _CLEAR_RESET_RSTGEN_RST_U0_ISPV2_TOP_WRAPPER_RST_C_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RST_U0_ISPV2_TOP_WRAPPER_RST_C_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_M31DPHY_HW_RSTN_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_M31DPHY_HW_RSTN_SHIFT, RSTN_U0_M31DPHY_HW_RSTN_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_M31DPHY_HW_RSTN_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_M31DPHY_HW_RSTN_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_M31DPHY_HW_RSTN_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_M31DPHY_HW_RSTN_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_SHIFT, RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_M31DPHY_RSTB09_ALWAYS_ON_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_N_PCLK_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PCLK_SHIFT, RSTN_U0_VIN_RST_N_PCLK_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PCLK_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PCLK_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PCLK_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PCLK_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_SHIFT, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF0_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_SHIFT, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF1_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_SHIFT, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF2_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_SHIFT, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_PIXEL_CLK_IF3_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_N_SYS_CLK_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_SYS_CLK_SHIFT, RSTN_U0_VIN_RST_N_SYS_CLK_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_N_SYS_CLK_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_SYS_CLK_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_N_SYS_CLK_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_N_SYS_CLK_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_P_AXIRD_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_P_AXIRD_SHIFT, RSTN_U0_VIN_RST_P_AXIRD_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_P_AXIRD_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_P_AXIRD_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_P_AXIRD_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_P_AXIRD_MASK)
#define _READ_RESET_STATUS_RSTGEN_RSTN_U0_VIN_RST_P_AXIWR_ 	saif_get_reg(CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_P_AXIWR_SHIFT, RSTN_U0_VIN_RST_P_AXIWR_MASK)
#define _ASSERT_RESET_RSTGEN_RSTN_U0_VIN_RST_P_AXIWR_ 	saif_assert_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_P_AXIWR_MASK)
#define _CLEAR_RESET_RSTGEN_RSTN_U0_VIN_RST_P_AXIWR_ 	saif_clear_rst(CRG_RSTGEN_SOFTWARE_RESET_ASSERT0_REG_ADDR, CRG_RSTGEN_SOFTWARE_RESET_STATUS0_REG_ADDR, RSTN_U0_VIN_RST_P_AXIWR_MASK)


#endif //_CRG_MACRO_H_
